//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.10 at 02:15:21 PM EET 
//

package com.kodingtech;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for Declaratie300Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Declaratie300Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="luna" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}IntInt1_12SType" />
 *       &lt;attribute name="an" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}IntInt2017_2100SType" />
 *       &lt;attribute name="bifa_interne" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}IntInt0_1SType" />
 *       &lt;attribute name="temei" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Int_listaTemeiSType" />
 *       &lt;attribute name="nume_declar" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str75" />
 *       &lt;attribute name="prenume_declar" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str75" />
 *       &lt;attribute name="functie_declar" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str50" />
 *       &lt;attribute name="cui" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}CuiSType" />
 *       &lt;attribute name="den" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str200" />
 *       &lt;attribute name="adresa" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str1000" />
 *       &lt;attribute name="telefon" type="{mfp:anaf:dgti:d300:declaratie:v6}Str15" />
 *       &lt;attribute name="fax" type="{mfp:anaf:dgti:d300:declaratie:v6}Str15" />
 *       &lt;attribute name="mail" type="{mfp:anaf:dgti:d300:declaratie:v6}Email200SType" />
 *       &lt;attribute name="banca" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str50" />
 *       &lt;attribute name="cont" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str50" />
 *       &lt;attribute name="caen" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaCaenSType" />
 *       &lt;attribute name="tip_decont" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaDecontSType" />
 *       &lt;attribute name="pro_rata" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}DblGen3_2_L_0d0_100d0SType" />
 *       &lt;attribute name="bifa_cereale" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaDaNuSType" />
 *       &lt;attribute name="bifa_mob" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaDaNuSType" />
 *       &lt;attribute name="bifa_disp" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaDaNuSType" />
 *       &lt;attribute name="bifa_cons" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaDaNuSType" />
 *       &lt;attribute name="solicit_ramb" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}Str_listaDaNuSType" />
 *       &lt;attribute name="nr_evid" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}IntStr23SType" />
 *       &lt;attribute name="totalPlata_A" use="required" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg18SType" />
 *       &lt;attribute name="R1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R2_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R3_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R3_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R4_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R5_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R5_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R5_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R5_1_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R6_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R6_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R7_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R7_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R7_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R7_1_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R8_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R8_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R9_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R9_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R10_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R10_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R11_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R11_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_1_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_2_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_2_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_3_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R12_3_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R13_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R14_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R15_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R16_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R16_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R17_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R17_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R18_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R18_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R18_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R18_1_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R19_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R19_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R20_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R20_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R20_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R20_1_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R21_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R21_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R22_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R22_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R23_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R23_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R24_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R24_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_1_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_2_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_2_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_3_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R25_3_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R43_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R44_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R26_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R26_1_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R27_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R27_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R28_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R29_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R30_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R30_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R31_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R32_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R33_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R34_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R35_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R36_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R37_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R38_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R39_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R40_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R41_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R42_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="nr_facturi" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="baza" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="tva" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="nr_facturi_primite" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="baza_primite" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="tva_primite" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="valoare_a" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="valoare_a1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="tva_a" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="tva_a1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="valoare_b" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="valoare_b1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="tva_b" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="tva_b1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="nr_fact_emise" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="total_baza" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="total_tva" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="cuiSuccesor" type="{mfp:anaf:dgti:d300:declaratie:v6}CifSType" />
 *       &lt;attribute name="R64_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R64_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R65_1" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="R65_2" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="total_precedent" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *       &lt;attribute name="total_curent" type="{mfp:anaf:dgti:d300:declaratie:v6}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "Declaratie300Type")
@XmlRootElement(name = "declaratie300", namespace = "mfp:anaf:dgti:d300:declaratie:v6")
public class Declaratie300Type {

    protected String key;

    protected String keyPassword;

    @XmlAttribute(name = "luna", required = true)
    protected int luna;
    @XmlAttribute(name = "an", required = true)
    protected int an;
    @XmlAttribute(name = "bifa_interne", required = true)
    @SerializedName("bifa_interne")
    protected int bifaInterne;
    @XmlAttribute(name = "temei", required = true)
    protected BigInteger temei;
    @SerializedName("nume_declar")
    @XmlAttribute(name = "nume_declar", required = true)
    protected String numeDeclar;
    @SerializedName("prenume_declar")
    @XmlAttribute(name = "prenume_declar", required = true)
    protected String prenumeDeclar;
    @SerializedName("functie_declar")
    @XmlAttribute(name = "functie_declar", required = true)
    protected String functieDeclar;
    @XmlAttribute(name = "cui", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cui;
    @XmlAttribute(name = "den", required = true)
    protected String den;
    @XmlAttribute(name = "adresa", required = true)
    protected String adresa;
    @XmlAttribute(name = "telefon")
    protected String telefon;
    @XmlAttribute(name = "fax")
    protected String fax;
    @XmlAttribute(name = "mail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mail;
    @XmlAttribute(name = "banca", required = true)
    protected String banca;
    @XmlAttribute(name = "cont", required = true)
    protected String cont;
    @XmlAttribute(name = "caen", required = true)
    protected String caen;
    @SerializedName("tip_decont")
    @XmlAttribute(name = "tip_decont", required = true)
    protected StrListaDecontSType tipDecont;
    @XmlAttribute(name = "pro_rata", required = true)
    protected double proRata;
    @SerializedName("bifa_cereale")
    @XmlAttribute(name = "bifa_cereale", required = true)
    protected StrListaDaNuSType bifaCereale;
    @SerializedName("bifa_mob")
    @XmlAttribute(name = "bifa_mob", required = true)
    protected StrListaDaNuSType bifaMob;
    @SerializedName("bifa_disp")
    @XmlAttribute(name = "bifa_disp", required = true)
    protected StrListaDaNuSType bifaDisp;
    @SerializedName("bifa_cons")
    @XmlAttribute(name = "bifa_cons", required = true)
    protected StrListaDaNuSType bifaCons;
    @SerializedName("solicit_ramb")
    @XmlAttribute(name = "solicit_ramb", required = true)
    protected StrListaDaNuSType solicitRamb;
    @SerializedName("nr_evid")
    @XmlAttribute(name = "nr_evid", required = true)
    protected BigInteger nrEvid;
    @SerializedName("totalPlata_A")
    @XmlAttribute(name = "totalPlata_A", required = true)
    protected long totalPlataA;
    @XmlAttribute(name = "R1_1")
    @SerializedName("R1_1")
    protected Long r11;
    @SerializedName("R2_1")
    @XmlAttribute(name = "R2_1")
    protected Long r21;
    @SerializedName("R3_1")
    @XmlAttribute(name = "R3_1")
    protected Long r31;
    @SerializedName("R3_1_1")
    @XmlAttribute(name = "R3_1_1")
    protected Long r311;
    @SerializedName("R4_1")
    @XmlAttribute(name = "R4_1")
    protected Long r41;
    @SerializedName("R5_1")
    @XmlAttribute(name = "R5_1")
    protected Long r51;
    @SerializedName("R5_2")
    @XmlAttribute(name = "R5_2")
    protected Long r52;
    @SerializedName("R5_1_1")
    @XmlAttribute(name = "R5_1_1")
    protected Long r511;
    @SerializedName("R5_1_2")
    @XmlAttribute(name = "R5_1_2")
    protected Long r512;
    @SerializedName("R6_1")
    @XmlAttribute(name = "R6_1")
    protected Long r61;
    @SerializedName("R6_2")
    @XmlAttribute(name = "R6_2")
    protected Long r62;
    @SerializedName("R7_1")
    @XmlAttribute(name = "R7_1")
    protected Long r71;
    @SerializedName("R7_2")
    @XmlAttribute(name = "R7_2")
    protected Long r72;
    @SerializedName("R7_1_1")
    @XmlAttribute(name = "R7_1_1")
    protected Long r711;
    @SerializedName("R7_1_2")
    @XmlAttribute(name = "R7_1_2")
    protected Long r712;
    @SerializedName("R8_1")
    @XmlAttribute(name = "R8_1")
    protected Long r81;
    @SerializedName("R8_2")
    @XmlAttribute(name = "R8_2")
    protected Long r82;
    @SerializedName("R9_1")
    @XmlAttribute(name = "R9_1")
    protected Long r91;
    @SerializedName("R9_2")
    @XmlAttribute(name = "R9_2")
    protected Long r92;
    @SerializedName("R10_1")
    @XmlAttribute(name = "R10_1")
    protected Long r101;
    @SerializedName("R10_2")
    @XmlAttribute(name = "R10_2")
    protected Long r102;
    @SerializedName("R11_1")
    @XmlAttribute(name = "R11_1")
    protected Long r111;
    @SerializedName("R11_2")
    @XmlAttribute(name = "R11_2")
    protected Long r112;
    @SerializedName("R12_1")
    @XmlAttribute(name = "R12_1")
    protected Long r121;
    @SerializedName("R12_2")
    @XmlAttribute(name = "R12_2")
    protected Long r122;
    @SerializedName("R12_1_1")
    @XmlAttribute(name = "R12_1_1")
    protected Long r1211;
    @SerializedName("R12_1_2")
    @XmlAttribute(name = "R12_1_2")
    protected Long r1212;
    @SerializedName("R12_2_1")
    @XmlAttribute(name = "R12_2_1")
    protected Long r1221;
    @SerializedName("R12_2_2")
    @XmlAttribute(name = "R12_2_2")
    protected Long r1222;
    @SerializedName("R12_3_1")
    @XmlAttribute(name = "R12_3_1")
    protected Long r1231;
    @SerializedName("R12_3_2")
    @XmlAttribute(name = "R12_3_2")
    protected Long r1232;
    @SerializedName("R13_1")
    @XmlAttribute(name = "R13_1")
    protected Long r131;
    @SerializedName("R14_1")
    @XmlAttribute(name = "R14_1")
    protected Long r141;
    @SerializedName("R15_1")
    @XmlAttribute(name = "R15_1")
    protected Long r151;
    @SerializedName("R16_1")
    @XmlAttribute(name = "R16_1")
    protected Long r161;
    @SerializedName("R16_2")
    @XmlAttribute(name = "R16_2")
    protected Long r162;
    @SerializedName("R17_1")
    @XmlAttribute(name = "R17_1")
    protected Long r171;
    @SerializedName("R17_2")
    @XmlAttribute(name = "R17_2")
    protected Long r172;
    @SerializedName("R18_1")
    @XmlAttribute(name = "R18_1")
    protected Long r181;
    @SerializedName("R18_2")
    @XmlAttribute(name = "R18_2")
    protected Long r182;
    @SerializedName("R18_1_1")
    @XmlAttribute(name = "R18_1_1")
    protected Long r1811;
    @SerializedName("R18_1_2")
    @XmlAttribute(name = "R18_1_2")
    protected Long r1812;
    @SerializedName("R19_1")
    @XmlAttribute(name = "R19_1")
    protected Long r191;
    @SerializedName("R19_2")
    @XmlAttribute(name = "R19_2")
    protected Long r192;
    @SerializedName("R20_1")
    @XmlAttribute(name = "R20_1")
    protected Long r201;
    @SerializedName("R20_2")
    @XmlAttribute(name = "R20_2")
    protected Long r202;
    @SerializedName("R20_1_1")
    @XmlAttribute(name = "R20_1_1")
    protected Long r2011;
    @SerializedName("R20_1_2")
    @XmlAttribute(name = "R20_1_2")
    protected Long r2012;
    @SerializedName("R21_1")
    @XmlAttribute(name = "R21_1")
    protected Long r211;
    @SerializedName("R21_2")
    @XmlAttribute(name = "R21_2")
    protected Long r212;
    @SerializedName("R22_1")
    @XmlAttribute(name = "R22_1")
    protected Long r221;
    @SerializedName("R22_2")
    @XmlAttribute(name = "R22_2")
    protected Long r222;
    @SerializedName("R23_1")
    @XmlAttribute(name = "R23_1")
    protected Long r231;
    @SerializedName("R23_2")
    @XmlAttribute(name = "R23_2")
    protected Long r232;
    @SerializedName("R24_1")
    @XmlAttribute(name = "R24_1")
    protected Long r241;
    @SerializedName("R24_2")
    @XmlAttribute(name = "R24_2")
    protected Long r242;
    @SerializedName("R25_1")
    @XmlAttribute(name = "R25_1")
    protected Long r251;
    @SerializedName("R25_2")
    @XmlAttribute(name = "R25_2")
    protected Long r252;
    @SerializedName("R25_1_1")
    @XmlAttribute(name = "R25_1_1")
    protected Long r2511;
    @SerializedName("R25_1_2")
    @XmlAttribute(name = "R25_1_2")
    protected Long r2512;
    @SerializedName("R25_2_1")
    @XmlAttribute(name = "R25_2_1")
    protected Long r2521;
    @SerializedName("R25_2_2")
    @XmlAttribute(name = "R25_2_2")
    protected Long r2522;
    @SerializedName("R25_3_1")
    @XmlAttribute(name = "R25_3_1")
    protected Long r2531;
    @SerializedName("R25_3_2")
    @XmlAttribute(name = "R25_3_2")
    protected Long r2532;
    @SerializedName("R43_2")
    @XmlAttribute(name = "R43_2")
    protected Long r432;
    @SerializedName("R44_2")
    @XmlAttribute(name = "R44_2")
    protected Long r442;
    @SerializedName("R26_1")
    @XmlAttribute(name = "R26_1")
    protected Long r261;
    @SerializedName("R26_1_1")
    @XmlAttribute(name = "R26_1_1")
    protected Long r2611;
    @SerializedName("R27_1")
    @XmlAttribute(name = "R27_1")
    protected Long r271;
    @SerializedName("R27_2")
    @XmlAttribute(name = "R27_2")
    protected Long r272;
    @SerializedName("R28_2")
    @XmlAttribute(name = "R28_2")
    protected Long r282;
    @SerializedName("R29_2")
    @XmlAttribute(name = "R29_2")
    protected Long r292;
    @SerializedName("R30_1")
    @XmlAttribute(name = "R30_1")
    protected Long r301;
    @SerializedName("R30_2")
    @XmlAttribute(name = "R30_2")
    protected Long r302;
    @SerializedName("R31_2")
    @XmlAttribute(name = "R31_2")
    protected Long r312;
    @SerializedName("R32_2")
    @XmlAttribute(name = "R32_2")
    protected Long r322;
    @SerializedName("R33_2")
    @XmlAttribute(name = "R33_2")
    protected Long r332;
    @SerializedName("R34_2")
    @XmlAttribute(name = "R34_2")
    protected Long r342;
    @SerializedName("R35_2")
    @XmlAttribute(name = "R35_2")
    protected Long r352;
    @SerializedName("R36_2")
    @XmlAttribute(name = "R36_2")
    protected Long r362;
    @SerializedName("R37_2")
    @XmlAttribute(name = "R37_2")
    protected Long r372;
    @SerializedName("R38_2")
    @XmlAttribute(name = "R38_2")
    protected Long r382;
    @SerializedName("R39_2")
    @XmlAttribute(name = "R39_2")
    protected Long r392;
    @SerializedName("R40_2")
    @XmlAttribute(name = "R40_2")
    protected Long r402;
    @SerializedName("R41_2")
    @XmlAttribute(name = "R41_2")
    protected Long r412;
    @SerializedName("R42_2")
    @XmlAttribute(name = "R42_2")
    protected Long r422;
    @XmlAttribute(name = "nr_facturi")
    @SerializedName("nr_facturi")
    protected Long nrFacturi;
    @XmlAttribute(name = "baza")
    protected Long baza;
    @XmlAttribute(name = "tva")
    protected Long tva;
    @SerializedName("nr_facturi_primite")
    @XmlAttribute(name = "nr_facturi_primite")
    protected Long nrFacturiPrimite;
    @SerializedName("baza_primite")
    @XmlAttribute(name = "baza_primite")
    protected Long bazaPrimite;
    @SerializedName("tva_primite")
    @XmlAttribute(name = "tva_primite")
    protected Long tvaPrimite;
    @SerializedName("valoare_a")
    @XmlAttribute(name = "valoare_a")
    protected Long valoareA;
    @SerializedName("valoare_a1")
    @XmlAttribute(name = "valoare_a1")
    protected Long valoareA1;
    @SerializedName("tva_a")
    @XmlAttribute(name = "tva_a")
    protected Long tvaA;
    @SerializedName("tva_a1")
    @XmlAttribute(name = "tva_a1")
    protected Long tvaA1;
    @SerializedName("valoare_b")
    @XmlAttribute(name = "valoare_b")
    protected Long valoareB;
    @SerializedName("valoare_11")
    @XmlAttribute(name = "valoare_b1")
    protected Long valoareB1;
    @SerializedName("tva_b")
    @XmlAttribute(name = "tva_b")
    protected Long tvaB;
    @SerializedName("tva_b1")
    @XmlAttribute(name = "tva_b1")
    protected Long tvaB1;
    @SerializedName("nr_fact_emise")
    @XmlAttribute(name = "nr_fact_emise")
    protected Long nrFactEmise;
    @XmlAttribute(name = "total_baza")
    @SerializedName("total_baza")
    protected Long totalBaza;
    @SerializedName("total_tva")
    @XmlAttribute(name = "total_tva")
    protected Long totalTva;
    @XmlAttribute(name = "cuiSuccesor")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cuiSuccesor;
    @XmlAttribute(name = "R64_1")
    @SerializedName("R64_1")
    protected Long r641;
    @XmlAttribute(name = "R64_2")
    @SerializedName("R64_2")
    protected Long r642;
    @SerializedName("R65_1")
    @XmlAttribute(name = "R65_1")
    protected Long r651;
    @SerializedName("R65_2")
    @XmlAttribute(name = "R65_2")
    protected Long r652;
    @SerializedName("total_precedent")
    @XmlAttribute(name = "total_precedent")
    protected Long totalPrecedent;
    @SerializedName("total_curent")
    @XmlAttribute(name = "total_curent")
    protected Long totalCurent;

    public String getKey() {
        return key;
    }

    public void setKey(String value) {
        key = value;
    }

    public String getKeyPassword() {
        return keyPassword;
    }

    public void setKeyPassword(String value) {
        keyPassword = value;
    }

    /**
     * Gets the value of the luna property.
     * 
     */
    public int getLuna() {
        return luna;
    }

    /**
     * Sets the value of the luna property.
     * 
     */
    public void setLuna(int value) {
        this.luna = value;
    }

    /**
     * Gets the value of the an property.
     * 
     */
    public int getAn() {
        return an;
    }

    /**
     * Sets the value of the an property.
     * 
     */
    public void setAn(int value) {
        this.an = value;
    }

    /**
     * Gets the value of the bifaInterne property.
     * 
     */
    public int getBifaInterne() {
        return bifaInterne;
    }

    /**
     * Sets the value of the bifaInterne property.
     * 
     */
    public void setBifaInterne(int value) {
        this.bifaInterne = value;
    }

    /**
     * Gets the value of the temei property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTemei() {
        return temei;
    }

    /**
     * Sets the value of the temei property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTemei(BigInteger value) {
        this.temei = value;
    }

    /**
     * Gets the value of the numeDeclar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumeDeclar() {
        return numeDeclar;
    }

    /**
     * Sets the value of the numeDeclar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumeDeclar(String value) {
        this.numeDeclar = value;
    }

    /**
     * Gets the value of the prenumeDeclar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPrenumeDeclar() {
        return prenumeDeclar;
    }

    /**
     * Sets the value of the prenumeDeclar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPrenumeDeclar(String value) {
        this.prenumeDeclar = value;
    }

    /**
     * Gets the value of the functieDeclar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFunctieDeclar() {
        return functieDeclar;
    }

    /**
     * Sets the value of the functieDeclar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFunctieDeclar(String value) {
        this.functieDeclar = value;
    }

    /**
     * Gets the value of the cui property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCui() {
        return cui;
    }

    /**
     * Sets the value of the cui property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCui(String value) {
        this.cui = value;
    }

    /**
     * Gets the value of the den property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDen() {
        return den;
    }

    /**
     * Sets the value of the den property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDen(String value) {
        this.den = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAdresa(String value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTelefon() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTelefon(String value) {
        this.telefon = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the banca property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBanca() {
        return banca;
    }

    /**
     * Sets the value of the banca property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBanca(String value) {
        this.banca = value;
    }

    /**
     * Gets the value of the cont property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCont() {
        return cont;
    }

    /**
     * Sets the value of the cont property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCont(String value) {
        this.cont = value;
    }

    /**
     * Gets the value of the caen property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCaen() {
        return caen;
    }

    /**
     * Sets the value of the caen property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCaen(String value) {
        this.caen = value;
    }

    /**
     * Gets the value of the tipDecont property.
     * 
     * @return possible object is {@link StrListaDecontSType }
     * 
     */
    public StrListaDecontSType getTipDecont() {
        return tipDecont;
    }

    /**
     * Sets the value of the tipDecont property.
     * 
     * @param value allowed object is {@link StrListaDecontSType }
     * 
     */
    public void setTipDecont(StrListaDecontSType value) {
        this.tipDecont = value;
    }

    /**
     * Gets the value of the proRata property.
     * 
     */
    public double getProRata() {
        return proRata;
    }

    /**
     * Sets the value of the proRata property.
     * 
     */
    public void setProRata(double value) {
        this.proRata = value;
    }

    /**
     * Gets the value of the bifaCereale property.
     * 
     * @return possible object is {@link StrListaDaNuSType }
     * 
     */
    public StrListaDaNuSType getBifaCereale() {
        return bifaCereale;
    }

    /**
     * Sets the value of the bifaCereale property.
     * 
     * @param value allowed object is {@link StrListaDaNuSType }
     * 
     */
    public void setBifaCereale(StrListaDaNuSType value) {
        this.bifaCereale = value;
    }

    /**
     * Gets the value of the bifaMob property.
     * 
     * @return possible object is {@link StrListaDaNuSType }
     * 
     */
    public StrListaDaNuSType getBifaMob() {
        return bifaMob;
    }

    /**
     * Sets the value of the bifaMob property.
     * 
     * @param value allowed object is {@link StrListaDaNuSType }
     * 
     */
    public void setBifaMob(StrListaDaNuSType value) {
        this.bifaMob = value;
    }

    /**
     * Gets the value of the bifaDisp property.
     * 
     * @return possible object is {@link StrListaDaNuSType }
     * 
     */
    public StrListaDaNuSType getBifaDisp() {
        return bifaDisp;
    }

    /**
     * Sets the value of the bifaDisp property.
     * 
     * @param value allowed object is {@link StrListaDaNuSType }
     * 
     */
    public void setBifaDisp(StrListaDaNuSType value) {
        this.bifaDisp = value;
    }

    /**
     * Gets the value of the bifaCons property.
     * 
     * @return possible object is {@link StrListaDaNuSType }
     * 
     */
    public StrListaDaNuSType getBifaCons() {
        return bifaCons;
    }

    /**
     * Sets the value of the bifaCons property.
     * 
     * @param value allowed object is {@link StrListaDaNuSType }
     * 
     */
    public void setBifaCons(StrListaDaNuSType value) {
        this.bifaCons = value;
    }

    /**
     * Gets the value of the solicitRamb property.
     * 
     * @return possible object is {@link StrListaDaNuSType }
     * 
     */
    public StrListaDaNuSType getSolicitRamb() {
        return solicitRamb;
    }

    /**
     * Sets the value of the solicitRamb property.
     * 
     * @param value allowed object is {@link StrListaDaNuSType }
     * 
     */
    public void setSolicitRamb(StrListaDaNuSType value) {
        this.solicitRamb = value;
    }

    /**
     * Gets the value of the nrEvid property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getNrEvid() {
        return nrEvid;
    }

    /**
     * Sets the value of the nrEvid property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setNrEvid(BigInteger value) {
        this.nrEvid = value;
    }

    /**
     * Gets the value of the totalPlataA property.
     * 
     */
    public long getTotalPlataA() {
        return totalPlataA;
    }

    /**
     * Sets the value of the totalPlataA property.
     * 
     */
    public void setTotalPlataA(long value) {
        this.totalPlataA = value;
    }

    /**
     * Gets the value of the r11 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR11() {
        return r11;
    }

    /**
     * Sets the value of the r11 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR11(Long value) {
        this.r11 = value;
    }

    /**
     * Gets the value of the r21 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR21() {
        return r21;
    }

    /**
     * Sets the value of the r21 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR21(Long value) {
        this.r21 = value;
    }

    /**
     * Gets the value of the r31 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR31() {
        return r31;
    }

    /**
     * Sets the value of the r31 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR31(Long value) {
        this.r31 = value;
    }

    /**
     * Gets the value of the r311 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR311() {
        return r311;
    }

    /**
     * Sets the value of the r311 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR311(Long value) {
        this.r311 = value;
    }

    /**
     * Gets the value of the r41 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR41() {
        return r41;
    }

    /**
     * Sets the value of the r41 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR41(Long value) {
        this.r41 = value;
    }

    /**
     * Gets the value of the r51 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR51() {
        return r51;
    }

    /**
     * Sets the value of the r51 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR51(Long value) {
        this.r51 = value;
    }

    /**
     * Gets the value of the r52 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR52() {
        return r52;
    }

    /**
     * Sets the value of the r52 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR52(Long value) {
        this.r52 = value;
    }

    /**
     * Gets the value of the r511 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR511() {
        return r511;
    }

    /**
     * Sets the value of the r511 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR511(Long value) {
        this.r511 = value;
    }

    /**
     * Gets the value of the r512 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR512() {
        return r512;
    }

    /**
     * Sets the value of the r512 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR512(Long value) {
        this.r512 = value;
    }

    /**
     * Gets the value of the r61 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR61() {
        return r61;
    }

    /**
     * Sets the value of the r61 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR61(Long value) {
        this.r61 = value;
    }

    /**
     * Gets the value of the r62 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR62() {
        return r62;
    }

    /**
     * Sets the value of the r62 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR62(Long value) {
        this.r62 = value;
    }

    /**
     * Gets the value of the r71 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR71() {
        return r71;
    }

    /**
     * Sets the value of the r71 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR71(Long value) {
        this.r71 = value;
    }

    /**
     * Gets the value of the r72 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR72() {
        return r72;
    }

    /**
     * Sets the value of the r72 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR72(Long value) {
        this.r72 = value;
    }

    /**
     * Gets the value of the r711 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR711() {
        return r711;
    }

    /**
     * Sets the value of the r711 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR711(Long value) {
        this.r711 = value;
    }

    /**
     * Gets the value of the r712 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR712() {
        return r712;
    }

    /**
     * Sets the value of the r712 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR712(Long value) {
        this.r712 = value;
    }

    /**
     * Gets the value of the r81 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR81() {
        return r81;
    }

    /**
     * Sets the value of the r81 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR81(Long value) {
        this.r81 = value;
    }

    /**
     * Gets the value of the r82 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR82() {
        return r82;
    }

    /**
     * Sets the value of the r82 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR82(Long value) {
        this.r82 = value;
    }

    /**
     * Gets the value of the r91 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR91() {
        return r91;
    }

    /**
     * Sets the value of the r91 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR91(Long value) {
        this.r91 = value;
    }

    /**
     * Gets the value of the r92 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR92() {
        return r92;
    }

    /**
     * Sets the value of the r92 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR92(Long value) {
        this.r92 = value;
    }

    /**
     * Gets the value of the r101 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR101() {
        return r101;
    }

    /**
     * Sets the value of the r101 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR101(Long value) {
        this.r101 = value;
    }

    /**
     * Gets the value of the r102 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR102() {
        return r102;
    }

    /**
     * Sets the value of the r102 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR102(Long value) {
        this.r102 = value;
    }

    /**
     * Gets the value of the r111 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR111() {
        return r111;
    }

    /**
     * Sets the value of the r111 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR111(Long value) {
        this.r111 = value;
    }

    /**
     * Gets the value of the r112 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR112() {
        return r112;
    }

    /**
     * Sets the value of the r112 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR112(Long value) {
        this.r112 = value;
    }

    /**
     * Gets the value of the r121 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR121() {
        return r121;
    }

    /**
     * Sets the value of the r121 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR121(Long value) {
        this.r121 = value;
    }

    /**
     * Gets the value of the r122 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR122() {
        return r122;
    }

    /**
     * Sets the value of the r122 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR122(Long value) {
        this.r122 = value;
    }

    /**
     * Gets the value of the r1211 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1211() {
        return r1211;
    }

    /**
     * Sets the value of the r1211 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1211(Long value) {
        this.r1211 = value;
    }

    /**
     * Gets the value of the r1212 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1212() {
        return r1212;
    }

    /**
     * Sets the value of the r1212 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1212(Long value) {
        this.r1212 = value;
    }

    /**
     * Gets the value of the r1221 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1221() {
        return r1221;
    }

    /**
     * Sets the value of the r1221 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1221(Long value) {
        this.r1221 = value;
    }

    /**
     * Gets the value of the r1222 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1222() {
        return r1222;
    }

    /**
     * Sets the value of the r1222 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1222(Long value) {
        this.r1222 = value;
    }

    /**
     * Gets the value of the r1231 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1231() {
        return r1231;
    }

    /**
     * Sets the value of the r1231 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1231(Long value) {
        this.r1231 = value;
    }

    /**
     * Gets the value of the r1232 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1232() {
        return r1232;
    }

    /**
     * Sets the value of the r1232 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1232(Long value) {
        this.r1232 = value;
    }

    /**
     * Gets the value of the r131 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR131() {
        return r131;
    }

    /**
     * Sets the value of the r131 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR131(Long value) {
        this.r131 = value;
    }

    /**
     * Gets the value of the r141 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR141() {
        return r141;
    }

    /**
     * Sets the value of the r141 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR141(Long value) {
        this.r141 = value;
    }

    /**
     * Gets the value of the r151 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR151() {
        return r151;
    }

    /**
     * Sets the value of the r151 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR151(Long value) {
        this.r151 = value;
    }

    /**
     * Gets the value of the r161 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR161() {
        return r161;
    }

    /**
     * Sets the value of the r161 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR161(Long value) {
        this.r161 = value;
    }

    /**
     * Gets the value of the r162 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR162() {
        return r162;
    }

    /**
     * Sets the value of the r162 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR162(Long value) {
        this.r162 = value;
    }

    /**
     * Gets the value of the r171 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR171() {
        return r171;
    }

    /**
     * Sets the value of the r171 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR171(Long value) {
        this.r171 = value;
    }

    /**
     * Gets the value of the r172 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR172() {
        return r172;
    }

    /**
     * Sets the value of the r172 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR172(Long value) {
        this.r172 = value;
    }

    /**
     * Gets the value of the r181 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR181() {
        return r181;
    }

    /**
     * Sets the value of the r181 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR181(Long value) {
        this.r181 = value;
    }

    /**
     * Gets the value of the r182 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR182() {
        return r182;
    }

    /**
     * Sets the value of the r182 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR182(Long value) {
        this.r182 = value;
    }

    /**
     * Gets the value of the r1811 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1811() {
        return r1811;
    }

    /**
     * Sets the value of the r1811 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1811(Long value) {
        this.r1811 = value;
    }

    /**
     * Gets the value of the r1812 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR1812() {
        return r1812;
    }

    /**
     * Sets the value of the r1812 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR1812(Long value) {
        this.r1812 = value;
    }

    /**
     * Gets the value of the r191 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR191() {
        return r191;
    }

    /**
     * Sets the value of the r191 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR191(Long value) {
        this.r191 = value;
    }

    /**
     * Gets the value of the r192 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR192() {
        return r192;
    }

    /**
     * Sets the value of the r192 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR192(Long value) {
        this.r192 = value;
    }

    /**
     * Gets the value of the r201 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR201() {
        return r201;
    }

    /**
     * Sets the value of the r201 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR201(Long value) {
        this.r201 = value;
    }

    /**
     * Gets the value of the r202 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR202() {
        return r202;
    }

    /**
     * Sets the value of the r202 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR202(Long value) {
        this.r202 = value;
    }

    /**
     * Gets the value of the r2011 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2011() {
        return r2011;
    }

    /**
     * Sets the value of the r2011 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2011(Long value) {
        this.r2011 = value;
    }

    /**
     * Gets the value of the r2012 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2012() {
        return r2012;
    }

    /**
     * Sets the value of the r2012 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2012(Long value) {
        this.r2012 = value;
    }

    /**
     * Gets the value of the r211 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR211() {
        return r211;
    }

    /**
     * Sets the value of the r211 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR211(Long value) {
        this.r211 = value;
    }

    /**
     * Gets the value of the r212 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR212() {
        return r212;
    }

    /**
     * Sets the value of the r212 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR212(Long value) {
        this.r212 = value;
    }

    /**
     * Gets the value of the r221 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR221() {
        return r221;
    }

    /**
     * Sets the value of the r221 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR221(Long value) {
        this.r221 = value;
    }

    /**
     * Gets the value of the r222 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR222() {
        return r222;
    }

    /**
     * Sets the value of the r222 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR222(Long value) {
        this.r222 = value;
    }

    /**
     * Gets the value of the r231 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR231() {
        return r231;
    }

    /**
     * Sets the value of the r231 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR231(Long value) {
        this.r231 = value;
    }

    /**
     * Gets the value of the r232 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR232() {
        return r232;
    }

    /**
     * Sets the value of the r232 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR232(Long value) {
        this.r232 = value;
    }

    /**
     * Gets the value of the r241 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR241() {
        return r241;
    }

    /**
     * Sets the value of the r241 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR241(Long value) {
        this.r241 = value;
    }

    /**
     * Gets the value of the r242 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR242() {
        return r242;
    }

    /**
     * Sets the value of the r242 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR242(Long value) {
        this.r242 = value;
    }

    /**
     * Gets the value of the r251 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR251() {
        return r251;
    }

    /**
     * Sets the value of the r251 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR251(Long value) {
        this.r251 = value;
    }

    /**
     * Gets the value of the r252 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR252() {
        return r252;
    }

    /**
     * Sets the value of the r252 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR252(Long value) {
        this.r252 = value;
    }

    /**
     * Gets the value of the r2511 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2511() {
        return r2511;
    }

    /**
     * Sets the value of the r2511 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2511(Long value) {
        this.r2511 = value;
    }

    /**
     * Gets the value of the r2512 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2512() {
        return r2512;
    }

    /**
     * Sets the value of the r2512 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2512(Long value) {
        this.r2512 = value;
    }

    /**
     * Gets the value of the r2521 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2521() {
        return r2521;
    }

    /**
     * Sets the value of the r2521 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2521(Long value) {
        this.r2521 = value;
    }

    /**
     * Gets the value of the r2522 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2522() {
        return r2522;
    }

    /**
     * Sets the value of the r2522 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2522(Long value) {
        this.r2522 = value;
    }

    /**
     * Gets the value of the r2531 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2531() {
        return r2531;
    }

    /**
     * Sets the value of the r2531 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2531(Long value) {
        this.r2531 = value;
    }

    /**
     * Gets the value of the r2532 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2532() {
        return r2532;
    }

    /**
     * Sets the value of the r2532 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2532(Long value) {
        this.r2532 = value;
    }

    /**
     * Gets the value of the r432 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR432() {
        return r432;
    }

    /**
     * Sets the value of the r432 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR432(Long value) {
        this.r432 = value;
    }

    /**
     * Gets the value of the r442 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR442() {
        return r442;
    }

    /**
     * Sets the value of the r442 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR442(Long value) {
        this.r442 = value;
    }

    /**
     * Gets the value of the r261 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR261() {
        return r261;
    }

    /**
     * Sets the value of the r261 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR261(Long value) {
        this.r261 = value;
    }

    /**
     * Gets the value of the r2611 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR2611() {
        return r2611;
    }

    /**
     * Sets the value of the r2611 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR2611(Long value) {
        this.r2611 = value;
    }

    /**
     * Gets the value of the r271 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR271() {
        return r271;
    }

    /**
     * Sets the value of the r271 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR271(Long value) {
        this.r271 = value;
    }

    /**
     * Gets the value of the r272 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR272() {
        return r272;
    }

    /**
     * Sets the value of the r272 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR272(Long value) {
        this.r272 = value;
    }

    /**
     * Gets the value of the r282 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR282() {
        return r282;
    }

    /**
     * Sets the value of the r282 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR282(Long value) {
        this.r282 = value;
    }

    /**
     * Gets the value of the r292 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR292() {
        return r292;
    }

    /**
     * Sets the value of the r292 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR292(Long value) {
        this.r292 = value;
    }

    /**
     * Gets the value of the r301 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR301() {
        return r301;
    }

    /**
     * Sets the value of the r301 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR301(Long value) {
        this.r301 = value;
    }

    /**
     * Gets the value of the r302 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR302() {
        return r302;
    }

    /**
     * Sets the value of the r302 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR302(Long value) {
        this.r302 = value;
    }

    /**
     * Gets the value of the r312 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR312() {
        return r312;
    }

    /**
     * Sets the value of the r312 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR312(Long value) {
        this.r312 = value;
    }

    /**
     * Gets the value of the r322 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR322() {
        return r322;
    }

    /**
     * Sets the value of the r322 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR322(Long value) {
        this.r322 = value;
    }

    /**
     * Gets the value of the r332 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR332() {
        return r332;
    }

    /**
     * Sets the value of the r332 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR332(Long value) {
        this.r332 = value;
    }

    /**
     * Gets the value of the r342 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR342() {
        return r342;
    }

    /**
     * Sets the value of the r342 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR342(Long value) {
        this.r342 = value;
    }

    /**
     * Gets the value of the r352 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR352() {
        return r352;
    }

    /**
     * Sets the value of the r352 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR352(Long value) {
        this.r352 = value;
    }

    /**
     * Gets the value of the r362 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR362() {
        return r362;
    }

    /**
     * Sets the value of the r362 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR362(Long value) {
        this.r362 = value;
    }

    /**
     * Gets the value of the r372 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR372() {
        return r372;
    }

    /**
     * Sets the value of the r372 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR372(Long value) {
        this.r372 = value;
    }

    /**
     * Gets the value of the r382 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR382() {
        return r382;
    }

    /**
     * Sets the value of the r382 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR382(Long value) {
        this.r382 = value;
    }

    /**
     * Gets the value of the r392 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR392() {
        return r392;
    }

    /**
     * Sets the value of the r392 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR392(Long value) {
        this.r392 = value;
    }

    /**
     * Gets the value of the r402 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR402() {
        return r402;
    }

    /**
     * Sets the value of the r402 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR402(Long value) {
        this.r402 = value;
    }

    /**
     * Gets the value of the r412 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR412() {
        return r412;
    }

    /**
     * Sets the value of the r412 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR412(Long value) {
        this.r412 = value;
    }

    /**
     * Gets the value of the r422 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR422() {
        return r422;
    }

    /**
     * Sets the value of the r422 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR422(Long value) {
        this.r422 = value;
    }

    /**
     * Gets the value of the nrFacturi property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getNrFacturi() {
        return nrFacturi;
    }

    /**
     * Sets the value of the nrFacturi property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setNrFacturi(Long value) {
        this.nrFacturi = value;
    }

    /**
     * Gets the value of the baza property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBaza() {
        return baza;
    }

    /**
     * Sets the value of the baza property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBaza(Long value) {
        this.baza = value;
    }

    /**
     * Gets the value of the tva property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva() {
        return tva;
    }

    /**
     * Sets the value of the tva property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva(Long value) {
        this.tva = value;
    }

    /**
     * Gets the value of the nrFacturiPrimite property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getNrFacturiPrimite() {
        return nrFacturiPrimite;
    }

    /**
     * Sets the value of the nrFacturiPrimite property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setNrFacturiPrimite(Long value) {
        this.nrFacturiPrimite = value;
    }

    /**
     * Gets the value of the bazaPrimite property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaPrimite() {
        return bazaPrimite;
    }

    /**
     * Sets the value of the bazaPrimite property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaPrimite(Long value) {
        this.bazaPrimite = value;
    }

    /**
     * Gets the value of the tvaPrimite property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaPrimite() {
        return tvaPrimite;
    }

    /**
     * Sets the value of the tvaPrimite property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaPrimite(Long value) {
        this.tvaPrimite = value;
    }

    /**
     * Gets the value of the valoareA property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getValoareA() {
        return valoareA;
    }

    /**
     * Sets the value of the valoareA property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setValoareA(Long value) {
        this.valoareA = value;
    }

    /**
     * Gets the value of the valoareA1 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getValoareA1() {
        return valoareA1;
    }

    /**
     * Sets the value of the valoareA1 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setValoareA1(Long value) {
        this.valoareA1 = value;
    }

    /**
     * Gets the value of the tvaA property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaA() {
        return tvaA;
    }

    /**
     * Sets the value of the tvaA property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaA(Long value) {
        this.tvaA = value;
    }

    /**
     * Gets the value of the tvaA1 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaA1() {
        return tvaA1;
    }

    /**
     * Sets the value of the tvaA1 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaA1(Long value) {
        this.tvaA1 = value;
    }

    /**
     * Gets the value of the valoareB property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getValoareB() {
        return valoareB;
    }

    /**
     * Sets the value of the valoareB property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setValoareB(Long value) {
        this.valoareB = value;
    }

    /**
     * Gets the value of the valoareB1 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getValoareB1() {
        return valoareB1;
    }

    /**
     * Sets the value of the valoareB1 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setValoareB1(Long value) {
        this.valoareB1 = value;
    }

    /**
     * Gets the value of the tvaB property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaB() {
        return tvaB;
    }

    /**
     * Sets the value of the tvaB property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaB(Long value) {
        this.tvaB = value;
    }

    /**
     * Gets the value of the tvaB1 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaB1() {
        return tvaB1;
    }

    /**
     * Sets the value of the tvaB1 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaB1(Long value) {
        this.tvaB1 = value;
    }

    /**
     * Gets the value of the nrFactEmise property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getNrFactEmise() {
        return nrFactEmise;
    }

    /**
     * Sets the value of the nrFactEmise property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setNrFactEmise(Long value) {
        this.nrFactEmise = value;
    }

    /**
     * Gets the value of the totalBaza property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTotalBaza() {
        return totalBaza;
    }

    /**
     * Sets the value of the totalBaza property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTotalBaza(Long value) {
        this.totalBaza = value;
    }

    /**
     * Gets the value of the totalTva property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTotalTva() {
        return totalTva;
    }

    /**
     * Sets the value of the totalTva property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTotalTva(Long value) {
        this.totalTva = value;
    }

    /**
     * Gets the value of the cuiSuccesor property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCuiSuccesor() {
        return cuiSuccesor;
    }

    /**
     * Sets the value of the cuiSuccesor property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCuiSuccesor(String value) {
        this.cuiSuccesor = value;
    }

    /**
     * Gets the value of the r641 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR641() {
        return r641;
    }

    /**
     * Sets the value of the r641 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR641(Long value) {
        this.r641 = value;
    }

    /**
     * Gets the value of the r642 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR642() {
        return r642;
    }

    /**
     * Sets the value of the r642 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR642(Long value) {
        this.r642 = value;
    }

    /**
     * Gets the value of the r651 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR651() {
        return r651;
    }

    /**
     * Sets the value of the r651 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR651(Long value) {
        this.r651 = value;
    }

    /**
     * Gets the value of the r652 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getR652() {
        return r652;
    }

    /**
     * Sets the value of the r652 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setR652(Long value) {
        this.r652 = value;
    }

    /**
     * Gets the value of the totalPrecedent property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTotalPrecedent() {
        return totalPrecedent;
    }

    /**
     * Sets the value of the totalPrecedent property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTotalPrecedent(Long value) {
        this.totalPrecedent = value;
    }

    /**
     * Gets the value of the totalCurent property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTotalCurent() {
        return totalCurent;
    }

    /**
     * Sets the value of the totalCurent property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTotalCurent(Long value) {
        this.totalCurent = value;
    }

}
