//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.10 at 02:15:21 PM EET 
//


package com.kodingtech;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kodingtech package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Declaratie300_QNAME = new QName("mfp:anaf:dgti:d300:declaratie:v6", "declaratie300");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kodingtech
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Declaratie300Type }
     * 
     */
    public Declaratie300Type createDeclaratie300Type() {
        return new Declaratie300Type();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Declaratie300Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mfp:anaf:dgti:d300:declaratie:v6", name = "declaratie300")
    public JAXBElement<Declaratie300Type> createDeclaratie300(Declaratie300Type value) {
        return new JAXBElement<Declaratie300Type>(_Declaratie300_QNAME, Declaratie300Type.class, null, value);
    }

}
