//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 10:24:33 AM EET 
//

package com.kodingtech.models;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for Declaratie390Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Declaratie390Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rezumat" type="{mfp:anaf:dgti:d390:declaratie:v2}RezumatType"/>
 *         &lt;element name="operatie" type="{mfp:anaf:dgti:d390:declaratie:v2}OperatieType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="luna" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntInt1_12SType" />
 *       &lt;attribute name="an" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntInt2017_2100SType" />
 *       &lt;attribute name="d_rec" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntInt0_1SType" />
 *       &lt;attribute name="nume_declar" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}Str75" />
 *       &lt;attribute name="prenume_declar" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}Str75" />
 *       &lt;attribute name="functie_declar" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}Str50" />
 *       &lt;attribute name="cui" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}CuiSType" />
 *       &lt;attribute name="den" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}Str200" />
 *       &lt;attribute name="adresa" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}Str1000" />
 *       &lt;attribute name="telefon" type="{mfp:anaf:dgti:d390:declaratie:v2}Str15" />
 *       &lt;attribute name="fax" type="{mfp:anaf:dgti:d390:declaratie:v2}Str15" />
 *       &lt;attribute name="mail" type="{mfp:anaf:dgti:d390:declaratie:v2}Email200SType" />
 *       &lt;attribute name="totalPlata_A" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.NONE)
@XmlType(name = "Declaratie390Type", propOrder = { "rezumat", "operatie" })
@XmlRootElement(name = "declaratie390", namespace = "mfp:anaf:dgti:d390:declaratie:v2")
public class Declaratie390Type {

    protected String key;

    protected String keyPassword;

    @XmlElement(required = true, namespace = "mfp:anaf:dgti:d390:declaratie:v2")
    protected RezumatType rezumat;
    @XmlElement(required = true, namespace = "mfp:anaf:dgti:d390:declaratie:v2")
    protected List<OperatieType> operatie;
    @XmlAttribute(name = "luna", required = true)
    protected int luna;
    @XmlAttribute(name = "an", required = true)
    protected int an;
    @SerializedName("d_rec")
    @XmlAttribute(name = "d_rec", required = true)
    protected int dRec;
    @SerializedName("nume_declar")
    @XmlAttribute(name = "nume_declar", required = true)
    protected String numeDeclar;
    @SerializedName("prenume_declar")
    @XmlAttribute(name = "prenume_declar", required = true)
    protected String prenumeDeclar;
    @SerializedName("functie_declar")
    @XmlAttribute(name = "functie_declar", required = true)
    protected String functieDeclar;
    @XmlAttribute(name = "cui", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cui;
    @XmlAttribute(name = "den", required = true)
    protected String den;
    @XmlAttribute(name = "adresa", required = true)
    protected String adresa;
    @XmlAttribute(name = "telefon")
    protected String telefon;
    @XmlAttribute(name = "fax")
    protected String fax;
    @XmlAttribute(name = "mail")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mail;
    @SerializedName("totalPlata_A")
    @XmlAttribute(name = "totalPlata_A", required = true)
    protected long totalPlataA;

    public String getKey() {
        return key;
    }

    public void setKey(String value) {
        key = value;
    }

    public String getKeyPassword() {
        return keyPassword;
    }

    public void setKeyPassword(String value) {
        keyPassword = value;
    }

    /**
     * Gets the value of the rezumat property.
     * 
     * @return possible object is {@link RezumatType }
     * 
     */
    public RezumatType getRezumat() {
        return rezumat;
    }

    /**
     * Sets the value of the rezumat property.
     * 
     * @param value allowed object is {@link RezumatType }
     * 
     */
    public void setRezumat(RezumatType value) {
        this.rezumat = value;
    }

    /**
     * Gets the value of the operatie property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the operatie property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOperatie().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link OperatieType
     * }
     * 
     * 
     */
    public List<OperatieType> getOperatie() {
        if (operatie == null) {
            operatie = new ArrayList<OperatieType>();
        }
        return this.operatie;
    }

    /**
     * Gets the value of the luna property.
     * 
     */
    public int getLuna() {
        return luna;
    }

    /**
     * Sets the value of the luna property.
     * 
     */
    public void setLuna(int value) {
        this.luna = value;
    }

    /**
     * Gets the value of the an property.
     * 
     */
    public int getAn() {
        return an;
    }

    /**
     * Sets the value of the an property.
     * 
     */
    public void setAn(int value) {
        this.an = value;
    }

    /**
     * Gets the value of the dRec property.
     * 
     */
    public int getDRec() {
        return dRec;
    }

    /**
     * Sets the value of the dRec property.
     * 
     */
    public void setDRec(int value) {
        this.dRec = value;
    }

    /**
     * Gets the value of the numeDeclar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNumeDeclar() {
        return numeDeclar;
    }

    /**
     * Sets the value of the numeDeclar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNumeDeclar(String value) {
        this.numeDeclar = value;
    }

    /**
     * Gets the value of the prenumeDeclar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPrenumeDeclar() {
        return prenumeDeclar;
    }

    /**
     * Sets the value of the prenumeDeclar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setPrenumeDeclar(String value) {
        this.prenumeDeclar = value;
    }

    /**
     * Gets the value of the functieDeclar property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFunctieDeclar() {
        return functieDeclar;
    }

    /**
     * Sets the value of the functieDeclar property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFunctieDeclar(String value) {
        this.functieDeclar = value;
    }

    /**
     * Gets the value of the cui property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCui() {
        return cui;
    }

    /**
     * Sets the value of the cui property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCui(String value) {
        this.cui = value;
    }

    /**
     * Gets the value of the den property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDen() {
        return den;
    }

    /**
     * Sets the value of the den property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDen(String value) {
        this.den = value;
    }

    /**
     * Gets the value of the adresa property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAdresa() {
        return adresa;
    }

    /**
     * Sets the value of the adresa property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setAdresa(String value) {
        this.adresa = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTelefon() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setTelefon(String value) {
        this.telefon = value;
    }

    /**
     * Gets the value of the fax property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFax() {
        return fax;
    }

    /**
     * Sets the value of the fax property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setFax(String value) {
        this.fax = value;
    }

    /**
     * Gets the value of the mail property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the totalPlataA property.
     * 
     */
    public long getTotalPlataA() {
        return totalPlataA;
    }

    /**
     * Sets the value of the totalPlataA property.
     * 
     */
    public void setTotalPlataA(long value) {
        this.totalPlataA = value;
    }

}
