//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 10:24:33 AM EET 
//

package com.kodingtech.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for RezumatType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RezumatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="nr_pag" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntPoz1SType" />
 *       &lt;attribute name="nrOPI" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntPoz10SType" />
 *       &lt;attribute name="bazaL" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *       &lt;attribute name="bazaT" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *       &lt;attribute name="bazaA" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *       &lt;attribute name="bazaP" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *       &lt;attribute name="bazaS" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *       &lt;attribute name="bazaR" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *       &lt;attribute name="total_baza" use="required" type="{mfp:anaf:dgti:d390:declaratie:v2}IntNeg18SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RezumatType")
public class RezumatType {

    @SerializedName("nr_pag")
    @XmlAttribute(name = "nr_pag", required = true)
    protected int nrPag;
    @XmlAttribute(name = "nrOPI", required = true)
    protected long nrOPI;
    @XmlAttribute(name = "bazaL", required = true)
    protected long bazaL;
    @XmlAttribute(name = "bazaT", required = true)
    protected long bazaT;
    @XmlAttribute(name = "bazaA", required = true)
    protected long bazaA;
    @XmlAttribute(name = "bazaP", required = true)
    protected long bazaP;
    @XmlAttribute(name = "bazaS", required = true)
    protected long bazaS;
    @XmlAttribute(name = "bazaR", required = true)
    protected long bazaR;
    @SerializedName("total_baza")
    @XmlAttribute(name = "total_baza", required = true)
    protected long totalBaza;

    /**
     * Gets the value of the nrPag property.
     * 
     */
    public int getNrPag() {
        return nrPag;
    }

    /**
     * Sets the value of the nrPag property.
     * 
     */
    public void setNrPag(int value) {
        this.nrPag = value;
    }

    /**
     * Gets the value of the nrOPI property.
     * 
     */
    public long getNrOPI() {
        return nrOPI;
    }

    /**
     * Sets the value of the nrOPI property.
     * 
     */
    public void setNrOPI(long value) {
        this.nrOPI = value;
    }

    /**
     * Gets the value of the bazaL property.
     * 
     */
    public long getBazaL() {
        return bazaL;
    }

    /**
     * Sets the value of the bazaL property.
     * 
     */
    public void setBazaL(long value) {
        this.bazaL = value;
    }

    /**
     * Gets the value of the bazaT property.
     * 
     */
    public long getBazaT() {
        return bazaT;
    }

    /**
     * Sets the value of the bazaT property.
     * 
     */
    public void setBazaT(long value) {
        this.bazaT = value;
    }

    /**
     * Gets the value of the bazaA property.
     * 
     */
    public long getBazaA() {
        return bazaA;
    }

    /**
     * Sets the value of the bazaA property.
     * 
     */
    public void setBazaA(long value) {
        this.bazaA = value;
    }

    /**
     * Gets the value of the bazaP property.
     * 
     */
    public long getBazaP() {
        return bazaP;
    }

    /**
     * Sets the value of the bazaP property.
     * 
     */
    public void setBazaP(long value) {
        this.bazaP = value;
    }

    /**
     * Gets the value of the bazaS property.
     * 
     */
    public long getBazaS() {
        return bazaS;
    }

    /**
     * Sets the value of the bazaS property.
     * 
     */
    public void setBazaS(long value) {
        this.bazaS = value;
    }

    /**
     * Gets the value of the bazaR property.
     * 
     */
    public long getBazaR() {
        return bazaR;
    }

    /**
     * Sets the value of the bazaR property.
     * 
     */
    public void setBazaR(long value) {
        this.bazaR = value;
    }

    /**
     * Gets the value of the totalBaza property.
     * 
     */
    public long getTotalBaza() {
        return totalBaza;
    }

    /**
     * Sets the value of the totalBaza property.
     * 
     */
    public void setTotalBaza(long value) {
        this.totalBaza = value;
    }

}
