//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for FacturiType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="FacturiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tip_factura" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt1_4SType" />
 *       &lt;attribute name="serie" type="{mfp:anaf:dgti:d394:declaratie:v3}Str20" />
 *       &lt;attribute name="nr" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Str20" />
 *       &lt;attribute name="baza24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="baza20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="baza19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="baza9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="baza5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FacturiType")
public class FacturiType {
    @SerializedName("tip_factura")
    @XmlAttribute(name = "tip_factura", required = true)
    protected int tipFactura;
    @XmlAttribute(name = "serie")
    protected String serie;
    @XmlAttribute(name = "nr", required = true)
    protected String nr;
    @XmlAttribute(name = "baza24")
    protected Long baza24;
    @XmlAttribute(name = "baza20")
    protected Long baza20;
    @XmlAttribute(name = "baza19")
    protected Long baza19;
    @XmlAttribute(name = "baza9")
    protected Long baza9;
    @XmlAttribute(name = "baza5")
    protected Long baza5;
    @XmlAttribute(name = "tva5")
    protected Long tva5;
    @XmlAttribute(name = "tva19")
    protected Long tva19;
    @XmlAttribute(name = "tva9")
    protected Long tva9;
    @XmlAttribute(name = "tva20")
    protected Long tva20;
    @XmlAttribute(name = "tva24")
    protected Long tva24;

    /**
     * Gets the value of the tipFactura property.
     * 
     */
    public int getTipFactura() {
        return tipFactura;
    }

    /**
     * Sets the value of the tipFactura property.
     * 
     */
    public void setTipFactura(int value) {
        this.tipFactura = value;
    }

    /**
     * Gets the value of the serie property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * Gets the value of the nr property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNr() {
        return nr;
    }

    /**
     * Sets the value of the nr property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNr(String value) {
        this.nr = value;
    }

    /**
     * Gets the value of the baza24 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBaza24() {
        return baza24;
    }

    /**
     * Sets the value of the baza24 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBaza24(Long value) {
        this.baza24 = value;
    }

    /**
     * Gets the value of the baza20 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBaza20() {
        return baza20;
    }

    /**
     * Sets the value of the baza20 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBaza20(Long value) {
        this.baza20 = value;
    }

    /**
     * Gets the value of the baza19 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBaza19() {
        return baza19;
    }

    /**
     * Sets the value of the baza19 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBaza19(Long value) {
        this.baza19 = value;
    }

    /**
     * Gets the value of the baza9 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBaza9() {
        return baza9;
    }

    /**
     * Sets the value of the baza9 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBaza9(Long value) {
        this.baza9 = value;
    }

    /**
     * Gets the value of the baza5 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBaza5() {
        return baza5;
    }

    /**
     * Sets the value of the baza5 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBaza5(Long value) {
        this.baza5 = value;
    }

    /**
     * Gets the value of the tva5 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva5() {
        return tva5;
    }

    /**
     * Sets the value of the tva5 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva5(Long value) {
        this.tva5 = value;
    }

    /**
     * Gets the value of the tva19 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva19() {
        return tva19;
    }

    /**
     * Sets the value of the tva19 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva19(Long value) {
        this.tva19 = value;
    }

    /**
     * Gets the value of the tva9 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva9() {
        return tva9;
    }

    /**
     * Sets the value of the tva9 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva9(Long value) {
        this.tva9 = value;
    }

    /**
     * Gets the value of the tva20 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva20() {
        return tva20;
    }

    /**
     * Sets the value of the tva20 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva20(Long value) {
        this.tva20 = value;
    }

    /**
     * Gets the value of the tva24 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva24() {
        return tva24;
    }

    /**
     * Sets the value of the tva24 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva24(Long value) {
        this.tva24 = value;
    }

}
