//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for InformatiiType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="InformatiiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="nrCui1" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrCui2" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrCui3" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrCui4" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nr_BF_i1" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="incasari_i1" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="incasari_i2" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="nrFacturi_terti" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrFacturi_benef" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrFacturi" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrFacturiL_PF" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="nrFacturiLS_PF" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="val_LS_PF" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDed24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDed20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDed19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDed9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDed5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDedAI24" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDedAI20" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDedAI19" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDedAI9" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaDedAI5" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaCol24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaCol20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaCol19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaCol9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaCol5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="incasari_ag" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="costuri_ag" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="marja_ag" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva_ag" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="pret_vanzare" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="pret_cumparare" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="marja_antic" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva_antic" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="solicit" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiPE" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiCR" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiCB" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiCI" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiA" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiB24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiB20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiB19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiB9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiB5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiS24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiS20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiS19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiS9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="achizitiiS5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="importB" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="acINecorp" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="livrariBI" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="BUN24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="BUN20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="BUN19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="BUN9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="BUN5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="valoareScutit" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="BunTI" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="Prest24" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="Prest20" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="Prest19" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="Prest9" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="Prest5" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="PrestScutit" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="LIntra" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="PrestIntra" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="Export" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="livINecorp" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *       &lt;attribute name="efectuat" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt0_1SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformatiiType")
public class InformatiiType {

    @XmlAttribute(name = "nrCui1", required = true)
    protected long nrCui1;
    @XmlAttribute(name = "nrCui2", required = true)
    protected long nrCui2;
    @XmlAttribute(name = "nrCui3", required = true)
    protected long nrCui3;
    @XmlAttribute(name = "nrCui4", required = true)
    protected long nrCui4;
    @SerializedName("nr_BF_i1")
    @XmlAttribute(name = "nr_BF_i1", required = true)
    protected long nrBFI1;
    @SerializedName("incasari_i1")
    @XmlAttribute(name = "incasari_i1", required = true)
    protected long incasariI1;
    @SerializedName("incasari_i2")
    @XmlAttribute(name = "incasari_i2", required = true)
    protected long incasariI2;
    @SerializedName("nrFacturi_terti")
    @XmlAttribute(name = "nrFacturi_terti", required = true)
    protected long nrFacturiTerti;
    @SerializedName("nrFacturi_benef")
    @XmlAttribute(name = "nrFacturi_benef", required = true)
    protected long nrFacturiBenef;
    @XmlAttribute(name = "nrFacturi", required = true)
    protected long nrFacturi;
    @SerializedName("nrFacturiL_PF")
    @XmlAttribute(name = "nrFacturiL_PF", required = true)
    protected long nrFacturiLPF;
    @SerializedName("nrFacturiLS_PF")
    @XmlAttribute(name = "nrFacturiLS_PF", required = true)
    protected long nrFacturiLSPF;
    @SerializedName("val_LS_PF")
    @XmlAttribute(name = "val_LS_PF", required = true)
    protected long valLSPF;
    @XmlAttribute(name = "tvaDed24")
    protected Long tvaDed24;
    @XmlAttribute(name = "tvaDed20")
    protected Long tvaDed20;
    @XmlAttribute(name = "tvaDed19")
    protected Long tvaDed19;
    @XmlAttribute(name = "tvaDed9")
    protected Long tvaDed9;
    @XmlAttribute(name = "tvaDed5")
    protected Long tvaDed5;
    @XmlAttribute(name = "tvaDedAI24", required = true)
    protected long tvaDedAI24;
    @XmlAttribute(name = "tvaDedAI20", required = true)
    protected long tvaDedAI20;
    @XmlAttribute(name = "tvaDedAI19", required = true)
    protected long tvaDedAI19;
    @XmlAttribute(name = "tvaDedAI9", required = true)
    protected long tvaDedAI9;
    @XmlAttribute(name = "tvaDedAI5", required = true)
    protected long tvaDedAI5;
    @XmlAttribute(name = "tvaCol24")
    protected Long tvaCol24;
    @XmlAttribute(name = "tvaCol20")
    protected Long tvaCol20;
    @XmlAttribute(name = "tvaCol19")
    protected Long tvaCol19;
    @XmlAttribute(name = "tvaCol9")
    protected Long tvaCol9;
    @XmlAttribute(name = "tvaCol5")
    protected Long tvaCol5;
    @SerializedName("incasari_ag")
    @XmlAttribute(name = "incasari_ag")
    protected Long incasariAg;
    @SerializedName("costuri_ag")
    @XmlAttribute(name = "costuri_ag")
    protected Long costuriAg;
    @SerializedName("marja_ag")
    @XmlAttribute(name = "marja_ag")
    protected Long marjaAg;
    @SerializedName("tva_ag")
    @XmlAttribute(name = "tva_ag")
    protected Long tvaAg;
    @SerializedName("pret_vanzare")
    @XmlAttribute(name = "pret_vanzare")
    protected Long pretVanzare;
    @SerializedName("pret_cumparare")
    @XmlAttribute(name = "pret_cumparare")
    protected Long pretCumparare;
    @SerializedName("marja_antic")
    @XmlAttribute(name = "marja_antic")
    protected Long marjaAntic;
    @SerializedName("tva_antic")
    @XmlAttribute(name = "tva_antic")
    protected Long tvaAntic;
    @XmlAttribute(name = "solicit", required = true)
    protected int solicit;
    @XmlAttribute(name = "achizitiiPE")
    protected Integer achizitiiPE;
    @XmlAttribute(name = "achizitiiCR")
    protected Integer achizitiiCR;
    @XmlAttribute(name = "achizitiiCB")
    protected Integer achizitiiCB;
    @XmlAttribute(name = "achizitiiCI")
    protected Integer achizitiiCI;
    @XmlAttribute(name = "achizitiiA")
    protected Integer achizitiiA;
    @XmlAttribute(name = "achizitiiB24")
    protected Integer achizitiiB24;
    @XmlAttribute(name = "achizitiiB20")
    protected Integer achizitiiB20;
    @XmlAttribute(name = "achizitiiB19")
    protected Integer achizitiiB19;
    @XmlAttribute(name = "achizitiiB9")
    protected Integer achizitiiB9;
    @XmlAttribute(name = "achizitiiB5")
    protected Integer achizitiiB5;
    @XmlAttribute(name = "achizitiiS24")
    protected Integer achizitiiS24;
    @XmlAttribute(name = "achizitiiS20")
    protected Integer achizitiiS20;
    @XmlAttribute(name = "achizitiiS19")
    protected Integer achizitiiS19;
    @XmlAttribute(name = "achizitiiS9")
    protected Integer achizitiiS9;
    @XmlAttribute(name = "achizitiiS5")
    protected Integer achizitiiS5;
    @XmlAttribute(name = "importB")
    protected Integer importB;
    @XmlAttribute(name = "acINecorp")
    protected Integer acINecorp;
    @XmlAttribute(name = "livrariBI")
    protected Integer livrariBI;
    @XmlAttribute(name = "BUN24")
    protected Integer bun24;
    @XmlAttribute(name = "BUN20")
    protected Integer bun20;
    @XmlAttribute(name = "BUN19")
    protected Integer bun19;
    @XmlAttribute(name = "BUN9")
    protected Integer bun9;
    @XmlAttribute(name = "BUN5")
    protected Integer bun5;
    @XmlAttribute(name = "valoareScutit")
    protected Integer valoareScutit;
    @XmlAttribute(name = "BunTI")
    protected Integer bunTI;
    @XmlAttribute(name = "Prest24")
    protected Integer prest24;
    @XmlAttribute(name = "Prest20")
    protected Integer prest20;
    @XmlAttribute(name = "Prest19")
    protected Integer prest19;
    @XmlAttribute(name = "Prest9")
    protected Integer prest9;
    @XmlAttribute(name = "Prest5")
    protected Integer prest5;
    @XmlAttribute(name = "PrestScutit")
    protected Integer prestScutit;
    @XmlAttribute(name = "LIntra")
    protected Integer lIntra;
    @XmlAttribute(name = "PrestIntra")
    protected Integer prestIntra;
    @XmlAttribute(name = "Export")
    protected Integer export;
    @XmlAttribute(name = "livINecorp")
    protected Integer livINecorp;
    @XmlAttribute(name = "efectuat")
    protected Integer efectuat;

    /**
     * Gets the value of the nrCui1 property.
     * 
     */
    public long getNrCui1() {
        return nrCui1;
    }

    /**
     * Sets the value of the nrCui1 property.
     * 
     */
    public void setNrCui1(long value) {
        this.nrCui1 = value;
    }

    /**
     * Gets the value of the nrCui2 property.
     * 
     */
    public long getNrCui2() {
        return nrCui2;
    }

    /**
     * Sets the value of the nrCui2 property.
     * 
     */
    public void setNrCui2(long value) {
        this.nrCui2 = value;
    }

    /**
     * Gets the value of the nrCui3 property.
     * 
     */
    public long getNrCui3() {
        return nrCui3;
    }

    /**
     * Sets the value of the nrCui3 property.
     * 
     */
    public void setNrCui3(long value) {
        this.nrCui3 = value;
    }

    /**
     * Gets the value of the nrCui4 property.
     * 
     */
    public long getNrCui4() {
        return nrCui4;
    }

    /**
     * Sets the value of the nrCui4 property.
     * 
     */
    public void setNrCui4(long value) {
        this.nrCui4 = value;
    }

    /**
     * Gets the value of the nrBFI1 property.
     * 
     */
    public long getNrBFI1() {
        return nrBFI1;
    }

    /**
     * Sets the value of the nrBFI1 property.
     * 
     */
    public void setNrBFI1(long value) {
        this.nrBFI1 = value;
    }

    /**
     * Gets the value of the incasariI1 property.
     * 
     */
    public long getIncasariI1() {
        return incasariI1;
    }

    /**
     * Sets the value of the incasariI1 property.
     * 
     */
    public void setIncasariI1(long value) {
        this.incasariI1 = value;
    }

    /**
     * Gets the value of the incasariI2 property.
     * 
     */
    public long getIncasariI2() {
        return incasariI2;
    }

    /**
     * Sets the value of the incasariI2 property.
     * 
     */
    public void setIncasariI2(long value) {
        this.incasariI2 = value;
    }

    /**
     * Gets the value of the nrFacturiTerti property.
     * 
     */
    public long getNrFacturiTerti() {
        return nrFacturiTerti;
    }

    /**
     * Sets the value of the nrFacturiTerti property.
     * 
     */
    public void setNrFacturiTerti(long value) {
        this.nrFacturiTerti = value;
    }

    /**
     * Gets the value of the nrFacturiBenef property.
     * 
     */
    public long getNrFacturiBenef() {
        return nrFacturiBenef;
    }

    /**
     * Sets the value of the nrFacturiBenef property.
     * 
     */
    public void setNrFacturiBenef(long value) {
        this.nrFacturiBenef = value;
    }

    /**
     * Gets the value of the nrFacturi property.
     * 
     */
    public long getNrFacturi() {
        return nrFacturi;
    }

    /**
     * Sets the value of the nrFacturi property.
     * 
     */
    public void setNrFacturi(long value) {
        this.nrFacturi = value;
    }

    /**
     * Gets the value of the nrFacturiLPF property.
     * 
     */
    public long getNrFacturiLPF() {
        return nrFacturiLPF;
    }

    /**
     * Sets the value of the nrFacturiLPF property.
     * 
     */
    public void setNrFacturiLPF(long value) {
        this.nrFacturiLPF = value;
    }

    /**
     * Gets the value of the nrFacturiLSPF property.
     * 
     */
    public long getNrFacturiLSPF() {
        return nrFacturiLSPF;
    }

    /**
     * Sets the value of the nrFacturiLSPF property.
     * 
     */
    public void setNrFacturiLSPF(long value) {
        this.nrFacturiLSPF = value;
    }

    /**
     * Gets the value of the valLSPF property.
     * 
     */
    public long getValLSPF() {
        return valLSPF;
    }

    /**
     * Sets the value of the valLSPF property.
     * 
     */
    public void setValLSPF(long value) {
        this.valLSPF = value;
    }

    /**
     * Gets the value of the tvaDed24 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaDed24() {
        return tvaDed24;
    }

    /**
     * Sets the value of the tvaDed24 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaDed24(Long value) {
        this.tvaDed24 = value;
    }

    /**
     * Gets the value of the tvaDed20 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaDed20() {
        return tvaDed20;
    }

    /**
     * Sets the value of the tvaDed20 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaDed20(Long value) {
        this.tvaDed20 = value;
    }

    /**
     * Gets the value of the tvaDed19 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaDed19() {
        return tvaDed19;
    }

    /**
     * Sets the value of the tvaDed19 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaDed19(Long value) {
        this.tvaDed19 = value;
    }

    /**
     * Gets the value of the tvaDed9 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaDed9() {
        return tvaDed9;
    }

    /**
     * Sets the value of the tvaDed9 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaDed9(Long value) {
        this.tvaDed9 = value;
    }

    /**
     * Gets the value of the tvaDed5 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaDed5() {
        return tvaDed5;
    }

    /**
     * Sets the value of the tvaDed5 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaDed5(Long value) {
        this.tvaDed5 = value;
    }

    /**
     * Gets the value of the tvaDedAI24 property.
     * 
     */
    public long getTvaDedAI24() {
        return tvaDedAI24;
    }

    /**
     * Sets the value of the tvaDedAI24 property.
     * 
     */
    public void setTvaDedAI24(long value) {
        this.tvaDedAI24 = value;
    }

    /**
     * Gets the value of the tvaDedAI20 property.
     * 
     */
    public long getTvaDedAI20() {
        return tvaDedAI20;
    }

    /**
     * Sets the value of the tvaDedAI20 property.
     * 
     */
    public void setTvaDedAI20(long value) {
        this.tvaDedAI20 = value;
    }

    /**
     * Gets the value of the tvaDedAI19 property.
     * 
     */
    public long getTvaDedAI19() {
        return tvaDedAI19;
    }

    /**
     * Sets the value of the tvaDedAI19 property.
     * 
     */
    public void setTvaDedAI19(long value) {
        this.tvaDedAI19 = value;
    }

    /**
     * Gets the value of the tvaDedAI9 property.
     * 
     */
    public long getTvaDedAI9() {
        return tvaDedAI9;
    }

    /**
     * Sets the value of the tvaDedAI9 property.
     * 
     */
    public void setTvaDedAI9(long value) {
        this.tvaDedAI9 = value;
    }

    /**
     * Gets the value of the tvaDedAI5 property.
     * 
     */
    public long getTvaDedAI5() {
        return tvaDedAI5;
    }

    /**
     * Sets the value of the tvaDedAI5 property.
     * 
     */
    public void setTvaDedAI5(long value) {
        this.tvaDedAI5 = value;
    }

    /**
     * Gets the value of the tvaCol24 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaCol24() {
        return tvaCol24;
    }

    /**
     * Sets the value of the tvaCol24 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaCol24(Long value) {
        this.tvaCol24 = value;
    }

    /**
     * Gets the value of the tvaCol20 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaCol20() {
        return tvaCol20;
    }

    /**
     * Sets the value of the tvaCol20 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaCol20(Long value) {
        this.tvaCol20 = value;
    }

    /**
     * Gets the value of the tvaCol19 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaCol19() {
        return tvaCol19;
    }

    /**
     * Sets the value of the tvaCol19 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaCol19(Long value) {
        this.tvaCol19 = value;
    }

    /**
     * Gets the value of the tvaCol9 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaCol9() {
        return tvaCol9;
    }

    /**
     * Sets the value of the tvaCol9 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaCol9(Long value) {
        this.tvaCol9 = value;
    }

    /**
     * Gets the value of the tvaCol5 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaCol5() {
        return tvaCol5;
    }

    /**
     * Sets the value of the tvaCol5 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaCol5(Long value) {
        this.tvaCol5 = value;
    }

    /**
     * Gets the value of the incasariAg property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getIncasariAg() {
        return incasariAg;
    }

    /**
     * Sets the value of the incasariAg property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setIncasariAg(Long value) {
        this.incasariAg = value;
    }

    /**
     * Gets the value of the costuriAg property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getCosturiAg() {
        return costuriAg;
    }

    /**
     * Sets the value of the costuriAg property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setCosturiAg(Long value) {
        this.costuriAg = value;
    }

    /**
     * Gets the value of the marjaAg property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getMarjaAg() {
        return marjaAg;
    }

    /**
     * Sets the value of the marjaAg property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setMarjaAg(Long value) {
        this.marjaAg = value;
    }

    /**
     * Gets the value of the tvaAg property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaAg() {
        return tvaAg;
    }

    /**
     * Sets the value of the tvaAg property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaAg(Long value) {
        this.tvaAg = value;
    }

    /**
     * Gets the value of the pretVanzare property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getPretVanzare() {
        return pretVanzare;
    }

    /**
     * Sets the value of the pretVanzare property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setPretVanzare(Long value) {
        this.pretVanzare = value;
    }

    /**
     * Gets the value of the pretCumparare property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getPretCumparare() {
        return pretCumparare;
    }

    /**
     * Sets the value of the pretCumparare property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setPretCumparare(Long value) {
        this.pretCumparare = value;
    }

    /**
     * Gets the value of the marjaAntic property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getMarjaAntic() {
        return marjaAntic;
    }

    /**
     * Sets the value of the marjaAntic property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setMarjaAntic(Long value) {
        this.marjaAntic = value;
    }

    /**
     * Gets the value of the tvaAntic property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaAntic() {
        return tvaAntic;
    }

    /**
     * Sets the value of the tvaAntic property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaAntic(Long value) {
        this.tvaAntic = value;
    }

    /**
     * Gets the value of the solicit property.
     * 
     */
    public int getSolicit() {
        return solicit;
    }

    /**
     * Sets the value of the solicit property.
     * 
     */
    public void setSolicit(int value) {
        this.solicit = value;
    }

    /**
     * Gets the value of the achizitiiPE property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiPE() {
        return achizitiiPE;
    }

    /**
     * Sets the value of the achizitiiPE property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiPE(Integer value) {
        this.achizitiiPE = value;
    }

    /**
     * Gets the value of the achizitiiCR property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiCR() {
        return achizitiiCR;
    }

    /**
     * Sets the value of the achizitiiCR property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiCR(Integer value) {
        this.achizitiiCR = value;
    }

    /**
     * Gets the value of the achizitiiCB property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiCB() {
        return achizitiiCB;
    }

    /**
     * Sets the value of the achizitiiCB property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiCB(Integer value) {
        this.achizitiiCB = value;
    }

    /**
     * Gets the value of the achizitiiCI property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiCI() {
        return achizitiiCI;
    }

    /**
     * Sets the value of the achizitiiCI property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiCI(Integer value) {
        this.achizitiiCI = value;
    }

    /**
     * Gets the value of the achizitiiA property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiA() {
        return achizitiiA;
    }

    /**
     * Sets the value of the achizitiiA property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiA(Integer value) {
        this.achizitiiA = value;
    }

    /**
     * Gets the value of the achizitiiB24 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiB24() {
        return achizitiiB24;
    }

    /**
     * Sets the value of the achizitiiB24 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiB24(Integer value) {
        this.achizitiiB24 = value;
    }

    /**
     * Gets the value of the achizitiiB20 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiB20() {
        return achizitiiB20;
    }

    /**
     * Sets the value of the achizitiiB20 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiB20(Integer value) {
        this.achizitiiB20 = value;
    }

    /**
     * Gets the value of the achizitiiB19 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiB19() {
        return achizitiiB19;
    }

    /**
     * Sets the value of the achizitiiB19 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiB19(Integer value) {
        this.achizitiiB19 = value;
    }

    /**
     * Gets the value of the achizitiiB9 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiB9() {
        return achizitiiB9;
    }

    /**
     * Sets the value of the achizitiiB9 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiB9(Integer value) {
        this.achizitiiB9 = value;
    }

    /**
     * Gets the value of the achizitiiB5 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiB5() {
        return achizitiiB5;
    }

    /**
     * Sets the value of the achizitiiB5 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiB5(Integer value) {
        this.achizitiiB5 = value;
    }

    /**
     * Gets the value of the achizitiiS24 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiS24() {
        return achizitiiS24;
    }

    /**
     * Sets the value of the achizitiiS24 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiS24(Integer value) {
        this.achizitiiS24 = value;
    }

    /**
     * Gets the value of the achizitiiS20 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiS20() {
        return achizitiiS20;
    }

    /**
     * Sets the value of the achizitiiS20 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiS20(Integer value) {
        this.achizitiiS20 = value;
    }

    /**
     * Gets the value of the achizitiiS19 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiS19() {
        return achizitiiS19;
    }

    /**
     * Sets the value of the achizitiiS19 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiS19(Integer value) {
        this.achizitiiS19 = value;
    }

    /**
     * Gets the value of the achizitiiS9 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiS9() {
        return achizitiiS9;
    }

    /**
     * Sets the value of the achizitiiS9 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiS9(Integer value) {
        this.achizitiiS9 = value;
    }

    /**
     * Gets the value of the achizitiiS5 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAchizitiiS5() {
        return achizitiiS5;
    }

    /**
     * Sets the value of the achizitiiS5 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAchizitiiS5(Integer value) {
        this.achizitiiS5 = value;
    }

    /**
     * Gets the value of the importB property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getImportB() {
        return importB;
    }

    /**
     * Sets the value of the importB property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setImportB(Integer value) {
        this.importB = value;
    }

    /**
     * Gets the value of the acINecorp property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getAcINecorp() {
        return acINecorp;
    }

    /**
     * Sets the value of the acINecorp property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setAcINecorp(Integer value) {
        this.acINecorp = value;
    }

    /**
     * Gets the value of the livrariBI property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getLivrariBI() {
        return livrariBI;
    }

    /**
     * Sets the value of the livrariBI property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setLivrariBI(Integer value) {
        this.livrariBI = value;
    }

    /**
     * Gets the value of the bun24 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getBUN24() {
        return bun24;
    }

    /**
     * Sets the value of the bun24 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setBUN24(Integer value) {
        this.bun24 = value;
    }

    /**
     * Gets the value of the bun20 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getBUN20() {
        return bun20;
    }

    /**
     * Sets the value of the bun20 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setBUN20(Integer value) {
        this.bun20 = value;
    }

    /**
     * Gets the value of the bun19 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getBUN19() {
        return bun19;
    }

    /**
     * Sets the value of the bun19 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setBUN19(Integer value) {
        this.bun19 = value;
    }

    /**
     * Gets the value of the bun9 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getBUN9() {
        return bun9;
    }

    /**
     * Sets the value of the bun9 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setBUN9(Integer value) {
        this.bun9 = value;
    }

    /**
     * Gets the value of the bun5 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getBUN5() {
        return bun5;
    }

    /**
     * Sets the value of the bun5 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setBUN5(Integer value) {
        this.bun5 = value;
    }

    /**
     * Gets the value of the valoareScutit property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getValoareScutit() {
        return valoareScutit;
    }

    /**
     * Sets the value of the valoareScutit property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setValoareScutit(Integer value) {
        this.valoareScutit = value;
    }

    /**
     * Gets the value of the bunTI property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getBunTI() {
        return bunTI;
    }

    /**
     * Sets the value of the bunTI property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setBunTI(Integer value) {
        this.bunTI = value;
    }

    /**
     * Gets the value of the prest24 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrest24() {
        return prest24;
    }

    /**
     * Sets the value of the prest24 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrest24(Integer value) {
        this.prest24 = value;
    }

    /**
     * Gets the value of the prest20 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrest20() {
        return prest20;
    }

    /**
     * Sets the value of the prest20 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrest20(Integer value) {
        this.prest20 = value;
    }

    /**
     * Gets the value of the prest19 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrest19() {
        return prest19;
    }

    /**
     * Sets the value of the prest19 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrest19(Integer value) {
        this.prest19 = value;
    }

    /**
     * Gets the value of the prest9 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrest9() {
        return prest9;
    }

    /**
     * Sets the value of the prest9 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrest9(Integer value) {
        this.prest9 = value;
    }

    /**
     * Gets the value of the prest5 property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrest5() {
        return prest5;
    }

    /**
     * Sets the value of the prest5 property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrest5(Integer value) {
        this.prest5 = value;
    }

    /**
     * Gets the value of the prestScutit property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrestScutit() {
        return prestScutit;
    }

    /**
     * Sets the value of the prestScutit property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrestScutit(Integer value) {
        this.prestScutit = value;
    }

    /**
     * Gets the value of the lIntra property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getLIntra() {
        return lIntra;
    }

    /**
     * Sets the value of the lIntra property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setLIntra(Integer value) {
        this.lIntra = value;
    }

    /**
     * Gets the value of the prestIntra property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getPrestIntra() {
        return prestIntra;
    }

    /**
     * Sets the value of the prestIntra property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setPrestIntra(Integer value) {
        this.prestIntra = value;
    }

    /**
     * Gets the value of the export property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getExport() {
        return export;
    }

    /**
     * Sets the value of the export property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setExport(Integer value) {
        this.export = value;
    }

    /**
     * Gets the value of the livINecorp property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getLivINecorp() {
        return livINecorp;
    }

    /**
     * Sets the value of the livINecorp property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setLivINecorp(Integer value) {
        this.livINecorp = value;
    }

    /**
     * Gets the value of the efectuat property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getEfectuat() {
        return efectuat;
    }

    /**
     * Sets the value of the efectuat property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setEfectuat(Integer value) {
        this.efectuat = value;
    }

}
