//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ListaType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ListaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="caen" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_listaCaenSType" />
 *       &lt;attribute name="cota" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_coteTVA2SType" />
 *       &lt;attribute name="operat" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt1_2SType" />
 *       &lt;attribute name="valoare" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListaType")
public class ListaType {

    @XmlAttribute(name = "caen", required = true)
    protected BigInteger caen;
    @XmlAttribute(name = "cota", required = true)
    protected BigInteger cota;
    @XmlAttribute(name = "operat", required = true)
    protected int operat;
    @XmlAttribute(name = "valoare", required = true)
    protected long valoare;
    @XmlAttribute(name = "tva", required = true)
    protected long tva;

    /**
     * Gets the value of the caen property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCaen() {
        return caen;
    }

    /**
     * Sets the value of the caen property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCaen(BigInteger value) {
        this.caen = value;
    }

    /**
     * Gets the value of the cota property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCota() {
        return cota;
    }

    /**
     * Sets the value of the cota property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCota(BigInteger value) {
        this.cota = value;
    }

    /**
     * Gets the value of the operat property.
     * 
     */
    public int getOperat() {
        return operat;
    }

    /**
     * Sets the value of the operat property.
     * 
     */
    public void setOperat(int value) {
        this.operat = value;
    }

    /**
     * Gets the value of the valoare property.
     * 
     */
    public long getValoare() {
        return valoare;
    }

    /**
     * Sets the value of the valoare property.
     * 
     */
    public void setValoare(long value) {
        this.valoare = value;
    }

    /**
     * Gets the value of the tva property.
     * 
     */
    public long getTva() {
        return tva;
    }

    /**
     * Sets the value of the tva property.
     * 
     */
    public void setTva(long value) {
        this.tva = value;
    }

}
