//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Op11Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Op11Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="nrFactPR" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="codPR" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Str_listaCodPRSType" />
 *       &lt;attribute name="bazaPR" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaPR" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Op11Type")
public class Op11Type {

    @XmlAttribute(name = "nrFactPR", required = true)
    protected long nrFactPR;
    @XmlAttribute(name = "codPR", required = true)
    protected String codPR;
    @XmlAttribute(name = "bazaPR", required = true)
    protected long bazaPR;
    @XmlAttribute(name = "tvaPR")
    protected Long tvaPR;

    /**
     * Gets the value of the nrFactPR property.
     * 
     */
    public long getNrFactPR() {
        return nrFactPR;
    }

    /**
     * Sets the value of the nrFactPR property.
     * 
     */
    public void setNrFactPR(long value) {
        this.nrFactPR = value;
    }

    /**
     * Gets the value of the codPR property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCodPR() {
        return codPR;
    }

    /**
     * Sets the value of the codPR property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCodPR(String value) {
        this.codPR = value;
    }

    /**
     * Gets the value of the bazaPR property.
     * 
     */
    public long getBazaPR() {
        return bazaPR;
    }

    /**
     * Sets the value of the bazaPR property.
     * 
     */
    public void setBazaPR(long value) {
        this.bazaPR = value;
    }

    /**
     * Gets the value of the tvaPR property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaPR() {
        return tvaPR;
    }

    /**
     * Sets the value of the tvaPR property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaPR(Long value) {
        this.tvaPR = value;
    }

}
