//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for Op1Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Op1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="op11" type="{mfp:anaf:dgti:d394:declaratie:v3}Op11Type" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tip" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Str_listaTipOperatieSType" />
 *       &lt;attribute name="tip_partener" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_tipPartenerOp1SType" />
 *       &lt;attribute name="cota" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_coteTVASType" />
 *       &lt;attribute name="cuiP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str50" />
 *       &lt;attribute name="denP" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Str200" />
 *       &lt;attribute name="taraP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str_listaTariSType" />
 *       &lt;attribute name="locP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str75" />
 *       &lt;attribute name="judP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str_listaJudSType" />
 *       &lt;attribute name="strP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str75" />
 *       &lt;attribute name="nrP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str50" />
 *       &lt;attribute name="blP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str50" />
 *       &lt;attribute name="apP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str50" />
 *       &lt;attribute name="detP" type="{mfp:anaf:dgti:d394:declaratie:v3}Str100" />
 *       &lt;attribute name="tip_document" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt1_5SType" />
 *       &lt;attribute name="nrFact" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="baza" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Op1Type", propOrder = { "op11" })
public class Op1Type {

    protected List<Op11Type> op11;
    @XmlAttribute(name = "tip", required = true)
    protected StrListaTipOperatieSType tip;
    @SerializedName("tip_partener")
    @XmlAttribute(name = "tip_partener", required = true)
    protected BigInteger tipPartener;
    @XmlAttribute(name = "cota", required = true)
    protected BigInteger cota;
    @XmlAttribute(name = "cuiP")
    protected String cuiP;
    @XmlAttribute(name = "denP", required = true)
    protected String denP;
    @XmlAttribute(name = "taraP")
    protected StrListaTariSType taraP;
    @XmlAttribute(name = "locP")
    protected String locP;
    @XmlAttribute(name = "judP")
    protected String judP;
    @XmlAttribute(name = "strP")
    protected String strP;
    @XmlAttribute(name = "nrP")
    protected String nrP;
    @XmlAttribute(name = "blP")
    protected String blP;
    @XmlAttribute(name = "apP")
    protected String apP;
    @XmlAttribute(name = "detP")
    protected String detP;
    @SerializedName("tip_document")
    @XmlAttribute(name = "tip_document")
    protected Integer tipDocument;
    @XmlAttribute(name = "nrFact", required = true)
    protected long nrFact;
    @XmlAttribute(name = "baza", required = true)
    protected long baza;
    @XmlAttribute(name = "tva")
    protected Long tva;

    /**
     * Gets the value of the op11 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the op11 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getOp11().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Op11Type }
     * 
     * 
     */
    public List<Op11Type> getOp11() {
        if (op11 == null) {
            op11 = new ArrayList<Op11Type>();
        }
        return this.op11;
    }

    /**
     * Gets the value of the tip property.
     * 
     * @return possible object is {@link StrListaTipOperatieSType }
     * 
     */
    public StrListaTipOperatieSType getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     * @param value allowed object is {@link StrListaTipOperatieSType }
     * 
     */
    public void setTip(StrListaTipOperatieSType value) {
        this.tip = value;
    }

    /**
     * Gets the value of the tipPartener property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTipPartener() {
        return tipPartener;
    }

    /**
     * Sets the value of the tipPartener property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTipPartener(BigInteger value) {
        this.tipPartener = value;
    }

    /**
     * Gets the value of the cota property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCota() {
        return cota;
    }

    /**
     * Sets the value of the cota property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCota(BigInteger value) {
        this.cota = value;
    }

    /**
     * Gets the value of the cuiP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCuiP() {
        return cuiP;
    }

    /**
     * Sets the value of the cuiP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCuiP(String value) {
        this.cuiP = value;
    }

    /**
     * Gets the value of the denP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDenP() {
        return denP;
    }

    /**
     * Sets the value of the denP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDenP(String value) {
        this.denP = value;
    }

    /**
     * Gets the value of the taraP property.
     * 
     * @return possible object is {@link StrListaTariSType }
     * 
     */
    public StrListaTariSType getTaraP() {
        return taraP;
    }

    /**
     * Sets the value of the taraP property.
     * 
     * @param value allowed object is {@link StrListaTariSType }
     * 
     */
    public void setTaraP(StrListaTariSType value) {
        this.taraP = value;
    }

    /**
     * Gets the value of the locP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLocP() {
        return locP;
    }

    /**
     * Sets the value of the locP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setLocP(String value) {
        this.locP = value;
    }

    /**
     * Gets the value of the judP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getJudP() {
        return judP;
    }

    /**
     * Sets the value of the judP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setJudP(String value) {
        this.judP = value;
    }

    /**
     * Gets the value of the strP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStrP() {
        return strP;
    }

    /**
     * Sets the value of the strP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setStrP(String value) {
        this.strP = value;
    }

    /**
     * Gets the value of the nrP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNrP() {
        return nrP;
    }

    /**
     * Sets the value of the nrP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNrP(String value) {
        this.nrP = value;
    }

    /**
     * Gets the value of the blP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBlP() {
        return blP;
    }

    /**
     * Sets the value of the blP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBlP(String value) {
        this.blP = value;
    }

    /**
     * Gets the value of the apP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getApP() {
        return apP;
    }

    /**
     * Sets the value of the apP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setApP(String value) {
        this.apP = value;
    }

    /**
     * Gets the value of the detP property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDetP() {
        return detP;
    }

    /**
     * Sets the value of the detP property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDetP(String value) {
        this.detP = value;
    }

    /**
     * Gets the value of the tipDocument property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getTipDocument() {
        return tipDocument;
    }

    /**
     * Sets the value of the tipDocument property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setTipDocument(Integer value) {
        this.tipDocument = value;
    }

    /**
     * Gets the value of the nrFact property.
     * 
     */
    public long getNrFact() {
        return nrFact;
    }

    /**
     * Sets the value of the nrFact property.
     * 
     */
    public void setNrFact(long value) {
        this.nrFact = value;
    }

    /**
     * Gets the value of the baza property.
     * 
     */
    public long getBaza() {
        return baza;
    }

    /**
     * Sets the value of the baza property.
     * 
     */
    public void setBaza(long value) {
        this.baza = value;
    }

    /**
     * Gets the value of the tva property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTva() {
        return tva;
    }

    /**
     * Sets the value of the tva property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTva(Long value) {
        this.tva = value;
    }

}
