//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for Rezumat1Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Rezumat1Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="detaliu" type="{mfp:anaf:dgti:d394:declaratie:v3}DetaliuType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tip_partener" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_tipPartenerSType" />
 *       &lt;attribute name="cota" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_coteTVASType" />
 *       &lt;attribute name="facturiL" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaL" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaL" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiLS" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaLS" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiA" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaA" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaA" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiAI" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaAI" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaAI" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiAS" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaAS" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiV" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaV" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiC" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaC" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaC" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="facturiN" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="document_N" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt1_5SType" />
 *       &lt;attribute name="bazaN" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rezumat1Type", propOrder = { "detaliu" })
public class Rezumat1Type {

    protected List<DetaliuType> detaliu;
    @SerializedName("tip_partener")
    @XmlAttribute(name = "tip_partener", required = true)
    protected BigInteger tipPartener;
    @XmlAttribute(name = "cota", required = true)
    protected BigInteger cota;
    @XmlAttribute(name = "facturiL")
    protected Long facturiL;
    @XmlAttribute(name = "bazaL")
    protected Long bazaL;
    @XmlAttribute(name = "tvaL")
    protected Long tvaL;
    @XmlAttribute(name = "facturiLS")
    protected Long facturiLS;
    @XmlAttribute(name = "bazaLS")
    protected Long bazaLS;
    @XmlAttribute(name = "facturiA")
    protected Long facturiA;
    @XmlAttribute(name = "bazaA")
    protected Long bazaA;
    @XmlAttribute(name = "tvaA")
    protected Long tvaA;
    @XmlAttribute(name = "facturiAI")
    protected Long facturiAI;
    @XmlAttribute(name = "bazaAI")
    protected Long bazaAI;
    @XmlAttribute(name = "tvaAI")
    protected Long tvaAI;
    @XmlAttribute(name = "facturiAS")
    protected Long facturiAS;
    @XmlAttribute(name = "bazaAS")
    protected Long bazaAS;
    @XmlAttribute(name = "facturiV")
    protected Long facturiV;
    @XmlAttribute(name = "bazaV")
    protected Long bazaV;
    @XmlAttribute(name = "facturiC")
    protected Long facturiC;
    @XmlAttribute(name = "bazaC")
    protected Long bazaC;
    @XmlAttribute(name = "tvaC")
    protected Long tvaC;
    @XmlAttribute(name = "facturiN")
    protected Long facturiN;
    @SerializedName("document_N")
    @XmlAttribute(name = "document_N")
    protected Integer documentN;
    @XmlAttribute(name = "bazaN")
    protected Long bazaN;

    /**
     * Gets the value of the detaliu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot.
     * Therefore any modification you make to the returned list will be present
     * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
     * for the detaliu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getDetaliu().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link DetaliuType }
     * 
     * 
     */
    public List<DetaliuType> getDetaliu() {
        if (detaliu == null) {
            detaliu = new ArrayList<DetaliuType>();
        }
        return this.detaliu;
    }

    /**
     * Gets the value of the tipPartener property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getTipPartener() {
        return tipPartener;
    }

    /**
     * Sets the value of the tipPartener property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setTipPartener(BigInteger value) {
        this.tipPartener = value;
    }

    /**
     * Gets the value of the cota property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCota() {
        return cota;
    }

    /**
     * Sets the value of the cota property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCota(BigInteger value) {
        this.cota = value;
    }

    /**
     * Gets the value of the facturiL property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiL() {
        return facturiL;
    }

    /**
     * Sets the value of the facturiL property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiL(Long value) {
        this.facturiL = value;
    }

    /**
     * Gets the value of the bazaL property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaL() {
        return bazaL;
    }

    /**
     * Sets the value of the bazaL property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaL(Long value) {
        this.bazaL = value;
    }

    /**
     * Gets the value of the tvaL property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaL() {
        return tvaL;
    }

    /**
     * Sets the value of the tvaL property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaL(Long value) {
        this.tvaL = value;
    }

    /**
     * Gets the value of the facturiLS property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiLS() {
        return facturiLS;
    }

    /**
     * Sets the value of the facturiLS property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiLS(Long value) {
        this.facturiLS = value;
    }

    /**
     * Gets the value of the bazaLS property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaLS() {
        return bazaLS;
    }

    /**
     * Sets the value of the bazaLS property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaLS(Long value) {
        this.bazaLS = value;
    }

    /**
     * Gets the value of the facturiA property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiA() {
        return facturiA;
    }

    /**
     * Sets the value of the facturiA property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiA(Long value) {
        this.facturiA = value;
    }

    /**
     * Gets the value of the bazaA property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaA() {
        return bazaA;
    }

    /**
     * Sets the value of the bazaA property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaA(Long value) {
        this.bazaA = value;
    }

    /**
     * Gets the value of the tvaA property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaA() {
        return tvaA;
    }

    /**
     * Sets the value of the tvaA property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaA(Long value) {
        this.tvaA = value;
    }

    /**
     * Gets the value of the facturiAI property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiAI() {
        return facturiAI;
    }

    /**
     * Sets the value of the facturiAI property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiAI(Long value) {
        this.facturiAI = value;
    }

    /**
     * Gets the value of the bazaAI property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaAI() {
        return bazaAI;
    }

    /**
     * Sets the value of the bazaAI property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaAI(Long value) {
        this.bazaAI = value;
    }

    /**
     * Gets the value of the tvaAI property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaAI() {
        return tvaAI;
    }

    /**
     * Sets the value of the tvaAI property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaAI(Long value) {
        this.tvaAI = value;
    }

    /**
     * Gets the value of the facturiAS property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiAS() {
        return facturiAS;
    }

    /**
     * Sets the value of the facturiAS property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiAS(Long value) {
        this.facturiAS = value;
    }

    /**
     * Gets the value of the bazaAS property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaAS() {
        return bazaAS;
    }

    /**
     * Sets the value of the bazaAS property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaAS(Long value) {
        this.bazaAS = value;
    }

    /**
     * Gets the value of the facturiV property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiV() {
        return facturiV;
    }

    /**
     * Sets the value of the facturiV property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiV(Long value) {
        this.facturiV = value;
    }

    /**
     * Gets the value of the bazaV property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaV() {
        return bazaV;
    }

    /**
     * Sets the value of the bazaV property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaV(Long value) {
        this.bazaV = value;
    }

    /**
     * Gets the value of the facturiC property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiC() {
        return facturiC;
    }

    /**
     * Sets the value of the facturiC property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiC(Long value) {
        this.facturiC = value;
    }

    /**
     * Gets the value of the bazaC property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaC() {
        return bazaC;
    }

    /**
     * Sets the value of the bazaC property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaC(Long value) {
        this.bazaC = value;
    }

    /**
     * Gets the value of the tvaC property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaC() {
        return tvaC;
    }

    /**
     * Sets the value of the tvaC property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaC(Long value) {
        this.tvaC = value;
    }

    /**
     * Gets the value of the facturiN property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getFacturiN() {
        return facturiN;
    }

    /**
     * Sets the value of the facturiN property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setFacturiN(Long value) {
        this.facturiN = value;
    }

    /**
     * Gets the value of the documentN property.
     * 
     * @return possible object is {@link Integer }
     * 
     */
    public Integer getDocumentN() {
        return documentN;
    }

    /**
     * Sets the value of the documentN property.
     * 
     * @param value allowed object is {@link Integer }
     * 
     */
    public void setDocumentN(Integer value) {
        this.documentN = value;
    }

    /**
     * Gets the value of the bazaN property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaN() {
        return bazaN;
    }

    /**
     * Sets the value of the bazaN property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaN(Long value) {
        this.bazaN = value;
    }

}
