//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import com.google.gson.annotations.SerializedName;

/**
 * <p>
 * Java class for Rezumat2Type complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Rezumat2Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cota" type="{mfp:anaf:dgti:d394:declaratie:v3}Int_coteTVA2SType" />
 *       &lt;attribute name="bazaFSLcod" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="TVAFSLcod" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="bazaFSL" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="TVAFSL" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="bazaFSA" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="TVAFSA" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="bazaFSAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="TVAFSAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="bazaBFAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="TVABFAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="nrFacturiL" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaL" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaL" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="nrFacturiA" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaA" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaA" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="nrFacturiAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntPoz15SType" />
 *       &lt;attribute name="bazaAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaAI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="baza_incasari_i1" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva_incasari_i1" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="baza_incasari_i2" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tva_incasari_i2" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="bazaL_PF" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *       &lt;attribute name="tvaL_PF" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntNeg15SType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Rezumat2Type")
public class Rezumat2Type {

    @XmlAttribute(name = "cota")
    protected BigInteger cota;
    @XmlAttribute(name = "bazaFSLcod", required = true)
    protected long bazaFSLcod;
    @XmlAttribute(name = "TVAFSLcod", required = true)
    protected long tvafsLcod;
    @XmlAttribute(name = "bazaFSL", required = true)
    protected long bazaFSL;
    @XmlAttribute(name = "TVAFSL", required = true)
    protected long tvafsl;
    @XmlAttribute(name = "bazaFSA", required = true)
    protected long bazaFSA;
    @XmlAttribute(name = "TVAFSA", required = true)
    protected long tvafsa;
    @XmlAttribute(name = "bazaFSAI", required = true)
    protected long bazaFSAI;
    @XmlAttribute(name = "TVAFSAI", required = true)
    protected long tvafsai;
    @XmlAttribute(name = "bazaBFAI", required = true)
    protected long bazaBFAI;
    @XmlAttribute(name = "TVABFAI", required = true)
    protected long tvabfai;
    @XmlAttribute(name = "nrFacturiL", required = true)
    protected long nrFacturiL;
    @XmlAttribute(name = "bazaL", required = true)
    protected long bazaL;
    @XmlAttribute(name = "tvaL", required = true)
    protected long tvaL;
    @XmlAttribute(name = "nrFacturiA", required = true)
    protected long nrFacturiA;
    @XmlAttribute(name = "bazaA", required = true)
    protected long bazaA;
    @XmlAttribute(name = "tvaA", required = true)
    protected long tvaA;
    @XmlAttribute(name = "nrFacturiAI", required = true)
    protected long nrFacturiAI;
    @XmlAttribute(name = "bazaAI", required = true)
    protected long bazaAI;
    @XmlAttribute(name = "tvaAI", required = true)
    protected long tvaAI;
    @SerializedName("baza_incasari_i1")
    @XmlAttribute(name = "baza_incasari_i1")
    protected Long bazaIncasariI1;
    @SerializedName("tva_incasari_i1")
    @XmlAttribute(name = "tva_incasari_i1")
    protected Long tvaIncasariI1;
    @SerializedName("baza_incasari_i2")
    @XmlAttribute(name = "baza_incasari_i2")
    protected Long bazaIncasariI2;
    @SerializedName("tva_incasari_i2")
    @XmlAttribute(name = "tva_incasari_i2")
    protected Long tvaIncasariI2;
    @SerializedName("bazaL_PF")
    @XmlAttribute(name = "bazaL_PF", required = true)
    protected long bazaLPF;
    @SerializedName("tvaL_PF")
    @XmlAttribute(name = "tvaL_PF", required = true)
    protected long tvaLPF;

    /**
     * Gets the value of the cota property.
     * 
     * @return possible object is {@link BigInteger }
     * 
     */
    public BigInteger getCota() {
        return cota;
    }

    /**
     * Sets the value of the cota property.
     * 
     * @param value allowed object is {@link BigInteger }
     * 
     */
    public void setCota(BigInteger value) {
        this.cota = value;
    }

    /**
     * Gets the value of the bazaFSLcod property.
     * 
     */
    public long getBazaFSLcod() {
        return bazaFSLcod;
    }

    /**
     * Sets the value of the bazaFSLcod property.
     * 
     */
    public void setBazaFSLcod(long value) {
        this.bazaFSLcod = value;
    }

    /**
     * Gets the value of the tvafsLcod property.
     * 
     */
    public long getTVAFSLcod() {
        return tvafsLcod;
    }

    /**
     * Sets the value of the tvafsLcod property.
     * 
     */
    public void setTVAFSLcod(long value) {
        this.tvafsLcod = value;
    }

    /**
     * Gets the value of the bazaFSL property.
     * 
     */
    public long getBazaFSL() {
        return bazaFSL;
    }

    /**
     * Sets the value of the bazaFSL property.
     * 
     */
    public void setBazaFSL(long value) {
        this.bazaFSL = value;
    }

    /**
     * Gets the value of the tvafsl property.
     * 
     */
    public long getTVAFSL() {
        return tvafsl;
    }

    /**
     * Sets the value of the tvafsl property.
     * 
     */
    public void setTVAFSL(long value) {
        this.tvafsl = value;
    }

    /**
     * Gets the value of the bazaFSA property.
     * 
     */
    public long getBazaFSA() {
        return bazaFSA;
    }

    /**
     * Sets the value of the bazaFSA property.
     * 
     */
    public void setBazaFSA(long value) {
        this.bazaFSA = value;
    }

    /**
     * Gets the value of the tvafsa property.
     * 
     */
    public long getTVAFSA() {
        return tvafsa;
    }

    /**
     * Sets the value of the tvafsa property.
     * 
     */
    public void setTVAFSA(long value) {
        this.tvafsa = value;
    }

    /**
     * Gets the value of the bazaFSAI property.
     * 
     */
    public long getBazaFSAI() {
        return bazaFSAI;
    }

    /**
     * Sets the value of the bazaFSAI property.
     * 
     */
    public void setBazaFSAI(long value) {
        this.bazaFSAI = value;
    }

    /**
     * Gets the value of the tvafsai property.
     * 
     */
    public long getTVAFSAI() {
        return tvafsai;
    }

    /**
     * Sets the value of the tvafsai property.
     * 
     */
    public void setTVAFSAI(long value) {
        this.tvafsai = value;
    }

    /**
     * Gets the value of the bazaBFAI property.
     * 
     */
    public long getBazaBFAI() {
        return bazaBFAI;
    }

    /**
     * Sets the value of the bazaBFAI property.
     * 
     */
    public void setBazaBFAI(long value) {
        this.bazaBFAI = value;
    }

    /**
     * Gets the value of the tvabfai property.
     * 
     */
    public long getTVABFAI() {
        return tvabfai;
    }

    /**
     * Sets the value of the tvabfai property.
     * 
     */
    public void setTVABFAI(long value) {
        this.tvabfai = value;
    }

    /**
     * Gets the value of the nrFacturiL property.
     * 
     */
    public long getNrFacturiL() {
        return nrFacturiL;
    }

    /**
     * Sets the value of the nrFacturiL property.
     * 
     */
    public void setNrFacturiL(long value) {
        this.nrFacturiL = value;
    }

    /**
     * Gets the value of the bazaL property.
     * 
     */
    public long getBazaL() {
        return bazaL;
    }

    /**
     * Sets the value of the bazaL property.
     * 
     */
    public void setBazaL(long value) {
        this.bazaL = value;
    }

    /**
     * Gets the value of the tvaL property.
     * 
     */
    public long getTvaL() {
        return tvaL;
    }

    /**
     * Sets the value of the tvaL property.
     * 
     */
    public void setTvaL(long value) {
        this.tvaL = value;
    }

    /**
     * Gets the value of the nrFacturiA property.
     * 
     */
    public long getNrFacturiA() {
        return nrFacturiA;
    }

    /**
     * Sets the value of the nrFacturiA property.
     * 
     */
    public void setNrFacturiA(long value) {
        this.nrFacturiA = value;
    }

    /**
     * Gets the value of the bazaA property.
     * 
     */
    public long getBazaA() {
        return bazaA;
    }

    /**
     * Sets the value of the bazaA property.
     * 
     */
    public void setBazaA(long value) {
        this.bazaA = value;
    }

    /**
     * Gets the value of the tvaA property.
     * 
     */
    public long getTvaA() {
        return tvaA;
    }

    /**
     * Sets the value of the tvaA property.
     * 
     */
    public void setTvaA(long value) {
        this.tvaA = value;
    }

    /**
     * Gets the value of the nrFacturiAI property.
     * 
     */
    public long getNrFacturiAI() {
        return nrFacturiAI;
    }

    /**
     * Sets the value of the nrFacturiAI property.
     * 
     */
    public void setNrFacturiAI(long value) {
        this.nrFacturiAI = value;
    }

    /**
     * Gets the value of the bazaAI property.
     * 
     */
    public long getBazaAI() {
        return bazaAI;
    }

    /**
     * Sets the value of the bazaAI property.
     * 
     */
    public void setBazaAI(long value) {
        this.bazaAI = value;
    }

    /**
     * Gets the value of the tvaAI property.
     * 
     */
    public long getTvaAI() {
        return tvaAI;
    }

    /**
     * Sets the value of the tvaAI property.
     * 
     */
    public void setTvaAI(long value) {
        this.tvaAI = value;
    }

    /**
     * Gets the value of the bazaIncasariI1 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaIncasariI1() {
        return bazaIncasariI1;
    }

    /**
     * Sets the value of the bazaIncasariI1 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaIncasariI1(Long value) {
        this.bazaIncasariI1 = value;
    }

    /**
     * Gets the value of the tvaIncasariI1 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaIncasariI1() {
        return tvaIncasariI1;
    }

    /**
     * Sets the value of the tvaIncasariI1 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaIncasariI1(Long value) {
        this.tvaIncasariI1 = value;
    }

    /**
     * Gets the value of the bazaIncasariI2 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getBazaIncasariI2() {
        return bazaIncasariI2;
    }

    /**
     * Sets the value of the bazaIncasariI2 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setBazaIncasariI2(Long value) {
        this.bazaIncasariI2 = value;
    }

    /**
     * Gets the value of the tvaIncasariI2 property.
     * 
     * @return possible object is {@link Long }
     * 
     */
    public Long getTvaIncasariI2() {
        return tvaIncasariI2;
    }

    /**
     * Sets the value of the tvaIncasariI2 property.
     * 
     * @param value allowed object is {@link Long }
     * 
     */
    public void setTvaIncasariI2(Long value) {
        this.tvaIncasariI2 = value;
    }

    /**
     * Gets the value of the bazaLPF property.
     * 
     */
    public long getBazaLPF() {
        return bazaLPF;
    }

    /**
     * Sets the value of the bazaLPF property.
     * 
     */
    public void setBazaLPF(long value) {
        this.bazaLPF = value;
    }

    /**
     * Gets the value of the tvaLPF property.
     * 
     */
    public long getTvaLPF() {
        return tvaLPF;
    }

    /**
     * Sets the value of the tvaLPF property.
     * 
     */
    public void setTvaLPF(long value) {
        this.tvaLPF = value;
    }

}
