//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for SerieFacturiType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SerieFacturiType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="tip" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}IntInt1_4SType" />
 *       &lt;attribute name="serieI" type="{mfp:anaf:dgti:d394:declaratie:v3}Str20" />
 *       &lt;attribute name="nrI" use="required" type="{mfp:anaf:dgti:d394:declaratie:v3}Str20" />
 *       &lt;attribute name="nrF" type="{mfp:anaf:dgti:d394:declaratie:v3}Str20" />
 *       &lt;attribute name="den" type="{mfp:anaf:dgti:d394:declaratie:v3}Str100" />
 *       &lt;attribute name="cui" type="{mfp:anaf:dgti:d394:declaratie:v3}CuiSType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SerieFacturiType")
public class SerieFacturiType {

    @XmlAttribute(name = "tip", required = true)
    protected int tip;
    @XmlAttribute(name = "serieI")
    protected String serieI;
    @XmlAttribute(name = "nrI", required = true)
    protected String nrI;
    @XmlAttribute(name = "nrF")
    protected String nrF;
    @XmlAttribute(name = "den")
    protected String den;
    @XmlAttribute(name = "cui")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String cui;

    /**
     * Gets the value of the tip property.
     * 
     */
    public int getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     */
    public void setTip(int value) {
        this.tip = value;
    }

    /**
     * Gets the value of the serieI property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSerieI() {
        return serieI;
    }

    /**
     * Sets the value of the serieI property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setSerieI(String value) {
        this.serieI = value;
    }

    /**
     * Gets the value of the nrI property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNrI() {
        return nrI;
    }

    /**
     * Sets the value of the nrI property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNrI(String value) {
        this.nrI = value;
    }

    /**
     * Gets the value of the nrF property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getNrF() {
        return nrF;
    }

    /**
     * Sets the value of the nrF property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setNrF(String value) {
        this.nrF = value;
    }

    /**
     * Gets the value of the den property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getDen() {
        return den;
    }

    /**
     * Sets the value of the den property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setDen(String value) {
        this.den = value;
    }

    /**
     * Gets the value of the cui property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCui() {
        return cui;
    }

    /**
     * Sets the value of the cui property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setCui(String value) {
        this.cui = value;
    }

}
