//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.13 at 04:09:50 PM EET 
//

package com.kodingtech.models.D394;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Str_tipOperatieSType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Str_tipOperatieSType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;maxLength value="256"/>
 *     &lt;enumeration value="I1"/>
 *     &lt;enumeration value="I2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Str_tipOperatieSType")
@XmlEnum
public enum StrTipOperatieSType {

    @XmlEnumValue("I1")
    I_1("I1"), @XmlEnumValue("I2")
    I_2("I2");

    private final String value;

    StrTipOperatieSType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StrTipOperatieSType fromValue(String v) {
        for (StrTipOperatieSType c : StrTipOperatieSType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
